import type { SupportedLocale } from "@/lib/i18n";

const copy = {
  en: { eyebrow: "Company finance", title: "Budgets", description: "Manage one audited budget cycle for each branch.", branch: "Branch", action: "Action", noBudget: "No budget configured", current: "Current budget", remaining: "Remaining", cycle: "Cycle", period: "Current period", status: "Status", active: "Active", manage: "Manage budget", setTitle: "Set branch budget", amount: "Amount", startDate: "Start date", customEndDate: "End date", monthly: "Monthly", yearly: "Yearly", custom: "Custom", save: "Set budget", saving: "Setting budget…", immutable: "The active budget period is immutable. Schedule a future change after this period ends.", funding: "Budget renewal requires Company Wallet funding.", openWallet: "Open Company Wallet", success: "Budget created. The active period is now protected from editing.", failure: "The budget could not be created. No financial state was changed.", back: "Back to budgets", viewBranch: "View branch" },
  ar: { eyebrow: "مالية الشركة", title: "الميزانيات", description: "إدارة دورة ميزانية مدققة واحدة لكل فرع.", branch: "الفرع", action: "الإجراء", noBudget: "لم يتم إعداد ميزانية", current: "الميزانية الحالية", remaining: "المتبقي", cycle: "الدورة", period: "الفترة الحالية", status: "الحالة", active: "نشط", manage: "إدارة الميزانية", setTitle: "تحديد ميزانية الفرع", amount: "المبلغ", startDate: "تاريخ البدء", customEndDate: "تاريخ الانتهاء", monthly: "شهري", yearly: "سنوي", custom: "مخصص", save: "تحديد الميزانية", saving: "جارٍ تحديد الميزانية…", immutable: "فترة الميزانية النشطة غير قابلة للتعديل. جَدول تغييراً مستقبلياً بعد انتهائها.", funding: "يتطلب تجديد الميزانية تمويل محفظة الشركة.", openWallet: "فتح محفظة الشركة", success: "تم إنشاء الميزانية. أصبحت الفترة النشطة محمية من التعديل.", failure: "تعذر إنشاء الميزانية. لم تتغير أي حالة مالية.", back: "العودة إلى الميزانيات", viewBranch: "عرض الفرع" },
  ms: { eyebrow: "Kewangan syarikat", title: "Bajet", description: "Urus satu kitaran bajet diaudit bagi setiap cawangan.", branch: "Cawangan", action: "Tindakan", noBudget: "Tiada bajet dikonfigurasi", current: "Bajet semasa", remaining: "Baki", cycle: "Kitaran", period: "Tempoh semasa", status: "Status", active: "Aktif", manage: "Urus bajet", setTitle: "Tetapkan bajet cawangan", amount: "Amaun", startDate: "Tarikh mula", customEndDate: "Tarikh tamat", monthly: "Bulanan", yearly: "Tahunan", custom: "Tersuai", save: "Tetapkan bajet", saving: "Menetapkan bajet…", immutable: "Tempoh bajet aktif tidak boleh diubah. Jadualkan perubahan masa hadapan selepas tempoh ini tamat.", funding: "Pembaharuan bajet memerlukan pembiayaan Dompet Syarikat.", openWallet: "Buka Dompet Syarikat", success: "Bajet dicipta. Tempoh aktif kini dilindungi daripada suntingan.", failure: "Bajet tidak dapat dicipta. Tiada keadaan kewangan diubah.", back: "Kembali ke bajet", viewBranch: "Lihat cawangan" },
} as const;

export function branchBudgetMessages(locale: SupportedLocale) { return copy[locale]; }
