import type { SupportedLocale } from "./i18n";

const messages = {
  en: {
    eyebrow: "Delivery operations", title: "Manage Drivers", intro: "Monitor Delivery Guy availability, current work, completed jobs and authorized live location.",
    driver: "Driver", state: "Account", active: "Active", deactivated: "Deactivated", availability: "Availability", current: "Current job", none: "No active job", completed: "Completed jobs", location: "Last location", noLocation: "No location", stale: "Stale / offline", profile: "Driver profile", contact: "Contact", vehicle: "Vehicle", notRecorded: "Not recorded", history: "Completed-job history", noHistory: "No completed jobs yet", actions: "Account actions", reset: "Send secure password reset", deactivate: "Deactivate driver", activate: "Activate driver", delete: "Delete driver", reason: "Deletion reason", confirm: "I understand access is permanently revoked.", blocked: "Resolve the active job before deactivating or deleting this driver.", recover: "Recover stuck job", release: "Return job to available pool", company: "Company", branch: "Branch", loading: "Loading live map…", map: "Live driver map", mapHelp: "Authorized operational location only. Route points expire under the delivery tracking retention policy.", mapMissing: "No current location is available, or a production map style has not been configured.", mapFailed: "The map is unavailable. Location timestamps and accuracy remain visible below.", routeMap: "Driver route map", back: "Back to drivers",
  },
  ar: {
    eyebrow: "عمليات التوصيل", title: "إدارة السائقين", intro: "راقب توافر سائق التوصيل والعمل الحالي والمهام المكتملة والموقع المباشر المصرح به.",
    driver: "السائق", state: "الحساب", active: "نشط", deactivated: "معطل", availability: "التوافر", current: "المهمة الحالية", none: "لا توجد مهمة نشطة", completed: "المهام المكتملة", location: "آخر موقع", noLocation: "لا يوجد موقع", stale: "قديم / غير متصل", profile: "ملف السائق", contact: "التواصل", vehicle: "المركبة", notRecorded: "غير مسجل", history: "سجل المهام المكتملة", noHistory: "لا توجد مهام مكتملة بعد", actions: "إجراءات الحساب", reset: "إرسال رابط آمن لإعادة تعيين كلمة المرور", deactivate: "تعطيل السائق", activate: "تنشيط السائق", delete: "حذف السائق", reason: "سبب الحذف", confirm: "أفهم أن الوصول سيُلغى نهائياً.", blocked: "عالج المهمة النشطة قبل تعطيل هذا السائق أو حذفه.", recover: "استعادة مهمة عالقة", release: "إعادة المهمة إلى قائمة المهام المتاحة", company: "الشركة", branch: "الفرع", loading: "جارٍ تحميل الخريطة المباشرة…", map: "خريطة السائق المباشرة", mapHelp: "موقع تشغيلي مصرح به فقط. تنتهي نقاط المسار وفق سياسة الاحتفاظ بتتبع التوصيل.", mapMissing: "لا يتوفر موقع حالي أو لم يتم إعداد نمط خريطة الإنتاج.", mapFailed: "الخريطة غير متاحة. تبقى أوقات الموقع ودقته ظاهرة أدناه.", routeMap: "خريطة مسار السائق", back: "العودة إلى السائقين",
  },
  ms: {
    eyebrow: "Operasi penghantaran", title: "Urus Pemandu", intro: "Pantau ketersediaan Penghantar, kerja semasa, tugasan selesai dan lokasi langsung yang dibenarkan.",
    driver: "Pemandu", state: "Akaun", active: "Aktif", deactivated: "Dinyahaktif", availability: "Ketersediaan", current: "Tugasan semasa", none: "Tiada tugasan aktif", completed: "Tugasan selesai", location: "Lokasi terakhir", noLocation: "Tiada lokasi", stale: "Lapuk / luar talian", profile: "Profil pemandu", contact: "Hubungan", vehicle: "Kenderaan", notRecorded: "Belum direkod", history: "Sejarah tugasan selesai", noHistory: "Belum ada tugasan selesai", actions: "Tindakan akaun", reset: "Hantar tetapan semula kata laluan selamat", deactivate: "Nyahaktif pemandu", activate: "Aktifkan pemandu", delete: "Padam pemandu", reason: "Sebab pemadaman", confirm: "Saya faham akses dibatalkan secara kekal.", blocked: "Selesaikan tugasan aktif sebelum menyahaktif atau memadam pemandu ini.", recover: "Pulihkan kerja tersekat", release: "Kembalikan kerja ke senarai tersedia", company: "Syarikat", branch: "Cawangan", loading: "Memuatkan peta langsung…", map: "Peta langsung pemandu", mapHelp: "Lokasi operasi yang dibenarkan sahaja. Titik laluan luput mengikut dasar pengekalan penjejakan.", mapMissing: "Tiada lokasi semasa, atau gaya peta produksi belum dikonfigurasi.", mapFailed: "Peta tidak tersedia. Masa dan ketepatan lokasi kekal kelihatan di bawah.", routeMap: "Peta laluan pemandu", back: "Kembali ke pemandu",
  },
} as const;

export function driverManagementMessages(locale: SupportedLocale = "en") {
  return messages[locale] ?? messages.en;
}
