import type { SupportedLocale } from "./i18n";

type Dictionary = Record<string, string>;

const en = {
  "common.activate": "Activate", "common.deactivate": "Deactivate", "common.status": "Status", "common.action": "Action",
  "common.save": "Save", "common.select": "Select", "common.upload": "Upload", "common.days": "{count} days", "common.day": "{count} day",
  "common.readOnly": "Read only", "common.systemMigration": "System / migration", "common.notSet": "Not set", "settings.updated": "Pricing settings saved.",
  "companies.eyebrow": "Axora master data", "companies.title": "Customer companies", "companies.description": "Axora owners approve each customer company before its branches, users and purchase requests can be managed.",
  "companies.register": "Company register", "companies.count": "{count} customer company records", "companies.code": "Code", "companies.company": "Company", "companies.industry": "Industry", "companies.contact": "Main contact", "companies.terms": "Payment terms", "companies.replaceLogo": "Replace logo", "companies.newLogo": "New approved logo for {name}", "companies.regenerate": "Regenerate theme",
  "companies.createTitle": "Register a customer company", "companies.createIntro": "Axora generates a stable company code and an accessible theme from the approved logo.", "companies.name": "Company name", "companies.billingCycle": "Billing cycle", "companies.monthly": "Monthly", "companies.perOrder": "Per order", "companies.weekly": "Weekly", "companies.info": "Company information", "companies.website": "Website URL (optional)", "companies.logo": "Approved company logo", "companies.logoHelp": "PNG, JPEG, or WebP up to 2 MB. Axora generates safe portal colours automatically; company users cannot edit them.", "companies.mainName": "Main contact", "companies.mainEmail": "Main email", "companies.mainPhone": "Main phone", "companies.billingName": "Billing contact", "companies.billingEmail": "Billing email", "companies.billingPhone": "Billing phone", "companies.billingAddress": "Billing address", "companies.notes": "Notes", "companies.submit": "Register company",
  "deliveries.eyebrow": "Delivery coordination", "deliveries.title": "Deliveries", "deliveries.manageDescription": "Create traceable delivery jobs, assign a driver, and monitor evidence. The customer receiver confirms quantities separately.", "deliveries.viewDescription": "Track delivery progress and customer-visible evidence for your permitted requests.", "deliveries.create": "Create delivery job", "deliveries.createIntro": "Axora snapshots the approved branch address and adds every remaining request line. Creating a job does not count as customer receipt.", "deliveries.request": "Approved paid request", "deliveries.selectRequest": "Select request", "deliveries.starts": "Window starts", "deliveries.ends": "Window ends", "deliveries.instructions": "Driver instructions", "deliveries.instructionsPlaceholder": "Access notes, approved contact instructions, handling requirements", "deliveries.submit": "Create delivery job", "deliveries.jobs": "Delivery jobs", "deliveries.count": "{count} traceable jobs", "deliveries.jobRequest": "Job / request", "deliveries.destination": "Destination", "deliveries.packages": "Packages", "deliveries.window": "Window", "deliveries.driver": "Driver", "deliveries.to": "to {date}", "deliveries.chooseDriver": "Choose driver", "deliveries.assign": "Assign", "deliveries.history": "Recorded delivery history", "deliveries.historyIntro": "Operational records are evidence; final receipt belongs to the assigned customer receiver.", "deliveries.requestLine": "Request line", "deliveries.companyProduct": "Company / product", "deliveries.expected": "Expected", "deliveries.actual": "Actual", "deliveries.evidenceQuantity": "Evidence quantity", "deliveries.evidenceIssue": "Evidence / issue",
  "finance.platformEyebrow": "Finance control", "finance.companyEyebrow": "Company billing", "finance.platformTitle": "Invoices and payments", "finance.companyTitle": "Your invoices and payment receipts", "finance.platformDescription": "Axora records payment and invoice evidence for reconciliation. It does not initiate or process online payments.", "finance.companyDescription": "Review customer invoices for your requests and the payment records recorded by Axora.", "finance.invoiceRegister": "Invoice register", "finance.invoiceCount": "{count} invoices", "finance.invoice": "Invoice", "finance.directionRequest": "Direction / request", "finance.counterparty": "Counterparty", "finance.dateDue": "Date / due", "finance.amount": "Amount", "finance.paid": "Paid", "finance.outstanding": "Outstanding", "finance.request": "Request", "finance.customer": "Customer", "finance.supplier": "Supplier", "finance.due": "Due {date}", "finance.paymentRegister": "Payment register", "finance.paymentIntro": "Evidence references for reconciliation", "finance.date": "Date", "finance.reference": "Reference", "finance.recordedBy": "Recorded by",
  "reports.platformEyebrow": "Axora management reporting", "reports.companyEyebrow": "Company request report", "reports.title": "Reports and reconciliation", "reports.platformDescription": "Export request records and reconcile Axora sales, internal buying costs and margins with request lines.", "reports.companyDescription": "Review your company's requested and approved spend, branch budgets and purchase request records.", "reports.sales": "Customer sales", "reports.salesNote": "Non-cancelled request lines", "reports.cost": "Internal buying cost", "reports.costNote": "Quantity-adjusted internal cost", "reports.margin": "Gross margin", "reports.fees": "Delivery fees", "reports.feesNote": "Reported separately", "reports.requested": "Requested value", "reports.requestedNote": "Estimated total, excluding cancelled requests", "reports.approved": "Approved spend", "reports.approvedNote": "Accepted by company approvers", "reports.pending": "Pending approval", "reports.pendingNote": "Awaiting an authorised decision", "reports.remaining": "Budget remaining", "reports.budgetCount": "{count} visible branch budgets configured", "reports.exports": "Available exports", "reports.exportsIntro": "UTF-8 CSV files open in Excel or LibreOffice", "reports.register": "Purchase request register", "reports.platformExport": "Customer companies, branches, workflow status, quantities, customer totals, internal buying costs and platform margin.", "reports.companyExport": "Your accessible branches, requested items, company approval status, fulfilment status and estimated customer totals.", "reports.download": "Download requests.csv", "reports.scoped": "Company-scoped export", "reports.scopedBody": "The downloaded register contains only records available to your signed-in account.", "reports.rule": "Reconciliation rule", "reports.ruleIntro": "Check figures before sharing them", "reports.platformRule": "Reconcile totals with request lines.", "reports.companyRule": "Approval controls committed spend.", "reports.platformRuleBody": "Customer sales and internal buying costs include quantity and exclude cancelled requests. Delivery fees are reported separately.", "reports.companyRuleBody": "Requested value includes non-cancelled requests. Approved spend includes only requests accepted by a company approver; branch remaining budget is calculated from approved requests in the current month.",
  "audit.eyebrow": "Accountability", "audit.title": "Audit history", "audit.description": "A read-only view of important database changes, who made them, and the recorded reason.", "audit.recent": "Recent changes", "audit.count": "Up to 500 newest records", "audit.when": "When", "audit.entity": "Entity", "audit.action": "Action", "audit.record": "Record", "audit.user": "User", "audit.reason": "Reason", "audit.empty": "No audit changes have been recorded yet.",
  "settings.eyebrow": "System control", "settings.title": "Settings and security", "settings.description": "Review the configuration that controls your Axora workspace.", "settings.workspaceConfig": "Workspace configuration", "settings.defaults": "Current operating defaults", "settings.workspace": "Workspace", "settings.platform": "Axora platform", "settings.assigned": "Assigned company", "settings.timezone": "Time zone", "settings.timezoneValue": "Malaysia time · Asia/Kuala_Lumpur (UTC+8)", "settings.currency": "Currency", "settings.currencyValue": "Malaysian ringgit (MYR)", "settings.protection": "Access and data protection", "settings.protectionIntro": "Security rules currently enforced", "settings.isolation": "Company isolation", "settings.isolationBody": "Users can access records only for their assigned company. The platform owner can administer all companies.", "settings.permissions": "Role and branch permissions", "settings.permissionsBody": "Requesters submit, authorised approvers decide, branch administrators manage one location, and company administrators manage the whole customer workspace.", "settings.accounts": "Protected accounts", "settings.accountsBody": "The owner, current signed-in user, and each company's last administrator cannot be deactivated accidentally.", "settings.documents": "Document limits", "settings.documentsBody": "Business attachments are limited to 2 MB; delivery evidence is limited to 5 MB. Allowed types are validated by the server.", "settings.pricing": "Request pricing configuration", "settings.pricingIntro": "Configure the estimated charges shown before company approval.", "settings.snapshot": "Charges are snapshotted when a request is submitted.", "settings.tax": "Tax / SST rate", "settings.taxHelp": "Use 0 when tax or SST does not apply.", "settings.fee": "Estimated delivery fee (RM)", "settings.feeHelp": "The final delivery charge is confirmed during fulfilment.", "settings.savePricing": "Save pricing settings", "settings.noCompany": "No company is available.", "settings.noCompanyBody": "Create or activate a company before configuring request pricing.", "settings.mode": "Current execution mode", "settings.modeIntro": "Read-only environment diagnostic", "settings.local": "Local sample mode", "settings.production": "Axora production mode", "settings.localBody": "Sample records are stored in memory and reset when the local server restarts.", "settings.productionBody": "Records are stored in PostgreSQL. Changes are persistent and company access controls are active.",
  "help.roleGuide": "Your role guide", "help.complete": "Tutorial complete", "help.continue": "Continue where you stopped", "help.progress": "{settled} of {total} steps completed or individually skipped. Skipped steps remain available.", "help.progressLabel": "{settled} of {total} tutorial steps finished", "help.review": "Review tutorial", "help.continueButton": "Continue tutorial", "help.ownerEyebrow": "Platform owner guide", "help.ownerTitle": "How Axora operates", "help.ownerDescription": "Axora owns the global catalog, company onboarding, buying and delivery for requests that customer companies approve and pay.", "help.ownerManuals": "Illustrated owner manuals", "help.companyEyebrow": "Company user guide", "help.companyTitle": "How your company requests through Axora", "help.companyDescription": "Your company controls people, branches, budgets, requests, approvals and Pay. Axora controls products, order preparation and delivery fulfilment.", "help.companyManuals": "Illustrated company manuals", "help.manualsIntro": "Open the step-by-step guide in English or Arabic.", "help.englishPdf": "English PDF", "help.arabicPdf": "العربية PDF", "help.ownerWorkflow": "Owner workflow", "help.ownerWorkflowIntro": "Set up once, then fulfil approved demand", "help.ownerRules": "Owner rules", "help.ownerRulesIntro": "Protect customer trust and operational evidence", "help.companyWorkflow": "Company workflow", "help.companyWorkflowIntro": "Assign responsibility before the first request", "help.companyRules": "Company rules", "help.companyRulesIntro": "Keep requests controlled and easy to audit",
  "access.eyebrow": "Access control", "access.title": "This page is not part of your role", "access.description": "Your account is signed in, but it does not have permission to open that workspace.", "access.none": "No data was shown", "access.body": "Use the navigation available to your role. Ask your company administrator if your responsibilities have changed.", "access.dashboard": "Back to dashboard", "access.settings": "Open settings", "access.help": "Open help",
  "notifications.eyebrow": "Personal workspace", "notifications.title": "Notifications", "notifications.description": "See only the procurement updates relevant to your role and adjust how routine events reach you.", "notifications.history": "Notification history", "notifications.inbox": "Activity inbox", "notifications.unread": "{count} unread updates", "notifications.current": "You are up to date", "notifications.markAll": "Mark all read", "notifications.marking": "Saving…", "notifications.open": "Open record", "notifications.mark": "Mark read", "notifications.empty": "No notifications yet", "notifications.emptyBody": "Assignments, decisions, deliveries, receipts, and finance exceptions will appear here.", "notifications.preferences": "Delivery preferences", "notifications.preferencesIntro": "Important account and security messages may still be sent when required.", "notifications.inApp": "In app", "notifications.email": "Email", "notifications.schedule": "Email delivery schedule", "notifications.immediate": "Immediately", "notifications.daily": "Next daily delivery window", "notifications.weekly": "Next weekly delivery window", "notifications.safety": "Delayed updates remain separate emails, not digests. Email subjects never contain passwords, setup tokens, or confidential procurement details.", "notifications.readSaved": "Notification marked as read.", "notifications.allReadSaved": "All notifications marked as read.", "notifications.preferenceSaved": "Delivery preference saved.",
} satisfies Dictionary;

const ar: Dictionary = {
  "common.activate":"تفعيل","common.deactivate":"تعطيل","common.status":"الحالة","common.action":"الإجراء","common.save":"حفظ","common.select":"اختيار","common.upload":"رفع","common.days":"{count} أيام","common.day":"يوم واحد","common.readOnly":"للقراءة فقط","common.systemMigration":"النظام / الترحيل","common.notSet":"غير محدد","settings.updated":"تم حفظ إعدادات التسعير.",
  "companies.eyebrow":"بيانات أكسورا الأساسية","companies.title":"الشركات العميلة","companies.description":"يعتمد مالكو أكسورا كل شركة قبل إدارة فروعها ومستخدميها وطلبات الشراء.","companies.register":"سجل الشركات","companies.count":"{count} من سجلات الشركات","companies.code":"الرمز","companies.company":"الشركة","companies.industry":"القطاع","companies.contact":"جهة الاتصال","companies.terms":"شروط الدفع","companies.replaceLogo":"استبدال الشعار","companies.newLogo":"شعار معتمد جديد لـ {name}","companies.regenerate":"إعادة توليد النسق","companies.createTitle":"تسجيل شركة عميلة","companies.createIntro":"تنشئ أكسورا رمزاً ثابتاً ونسقاً قابلاً للوصول من الشعار المعتمد.","companies.name":"اسم الشركة","companies.billingCycle":"دورة الفوترة","companies.monthly":"شهري","companies.perOrder":"لكل طلب","companies.weekly":"أسبوعي","companies.info":"معلومات الشركة","companies.website":"رابط الموقع (اختياري)","companies.logo":"شعار الشركة المعتمد","companies.logoHelp":"PNG أو JPEG أو WebP حتى 2 ميغابايت. تولد أكسورا ألواناً آمنة تلقائياً ولا يعدلها مستخدمو الشركة.","companies.mainName":"جهة الاتصال الرئيسية","companies.mainEmail":"البريد الرئيسي","companies.mainPhone":"الهاتف الرئيسي","companies.billingName":"جهة اتصال الفوترة","companies.billingEmail":"بريد الفوترة","companies.billingPhone":"هاتف الفوترة","companies.billingAddress":"عنوان الفوترة","companies.notes":"ملاحظات","companies.submit":"تسجيل الشركة",
  "deliveries.eyebrow":"تنسيق التسليم","deliveries.title":"التسليمات","deliveries.manageDescription":"أنشئ مهام قابلة للتتبع واسند سائقاً وراقب الدليل، ويؤكد مستلم العميل الكميات بشكل مستقل.","deliveries.viewDescription":"تابع تقدم التسليم والدليل الظاهر للعميل ضمن نطاقك.","deliveries.create":"إنشاء مهمة تسليم","deliveries.createIntro":"تحفظ أكسورا عنوان الفرع المعتمد وتضيف البنود المتبقية. إنشاء المهمة ليس استلاماً من العميل.","deliveries.request":"طلب معتمد ومدفوع","deliveries.selectRequest":"اختر الطلب","deliveries.starts":"بداية النافذة","deliveries.ends":"نهاية النافذة","deliveries.instructions":"تعليمات السائق","deliveries.instructionsPlaceholder":"تعليمات الدخول والاتصال المعتمد والتعامل","deliveries.submit":"إنشاء المهمة","deliveries.jobs":"مهام التسليم","deliveries.count":"{count} من المهام القابلة للتتبع","deliveries.jobRequest":"المهمة / الطلب","deliveries.destination":"الوجهة","deliveries.packages":"الطرود","deliveries.window":"النافذة","deliveries.driver":"السائق","deliveries.to":"إلى {date}","deliveries.chooseDriver":"اختر السائق","deliveries.assign":"إسناد","deliveries.history":"سجل التسليم","deliveries.historyIntro":"السجلات التشغيلية دليل، والاستلام النهائي مسؤولية مستلم العميل المعين.","deliveries.requestLine":"بند الطلب","deliveries.companyProduct":"الشركة / المنتج","deliveries.expected":"المتوقع","deliveries.actual":"الفعلي","deliveries.evidenceQuantity":"كمية الدليل","deliveries.evidenceIssue":"الدليل / المشكلة",
  "finance.platformEyebrow":"ضبط المالية","finance.companyEyebrow":"فوترة الشركة","finance.platformTitle":"الفواتير والمدفوعات","finance.companyTitle":"فواتيرك وإيصالات الدفع","finance.platformDescription":"تسجل أكسورا أدلة الدفع والفواتير للتسوية ولا تنفذ دفعاً إلكترونياً.","finance.companyDescription":"راجع فواتير العميل وإيصالات الدفع التي سجلتها أكسورا.","finance.invoiceRegister":"سجل الفواتير","finance.invoiceCount":"{count} من الفواتير","finance.invoice":"الفاتورة","finance.directionRequest":"الاتجاه / الطلب","finance.counterparty":"الطرف المقابل","finance.dateDue":"التاريخ / الاستحقاق","finance.amount":"المبلغ","finance.paid":"المدفوع","finance.outstanding":"المتبقي","finance.request":"الطلب","finance.customer":"العميل","finance.supplier":"المورد","finance.due":"يستحق {date}","finance.paymentRegister":"سجل المدفوعات","finance.paymentIntro":"مراجع الأدلة للتسوية","finance.date":"التاريخ","finance.reference":"المرجع","finance.recordedBy":"سجله",
  "reports.platformEyebrow":"تقارير إدارة أكسورا","reports.companyEyebrow":"تقرير مشتريات الشركة","reports.title":"التقارير والتسوية","reports.platformDescription":"صدر سجلات الطلبات وطابق مبيعات أكسورا وتكاليف الشراء الداخلية والهامش مع بنود الطلب.","reports.companyDescription":"راجع قيمة الطلبات المعتمدة والميزانيات وسجلات الشراء.","reports.sales":"مبيعات العملاء","reports.salesNote":"بنود غير ملغاة","reports.cost":"تكلفة الشراء الداخلية","reports.costNote":"تكلفة داخلية حسب الكمية","reports.margin":"الهامش الإجمالي","reports.fees":"رسوم التسليم","reports.feesNote":"تظهر منفصلة","reports.requested":"القيمة المطلوبة","reports.requestedNote":"التقدير دون الطلبات الملغاة","reports.approved":"الإنفاق المعتمد","reports.approvedNote":"قبله معتمدو الشركة","reports.pending":"اعتماد معلق","reports.pendingNote":"ينتظر قراراً مخولاً","reports.remaining":"الميزانية المتبقية","reports.budgetCount":"{count} من ميزانيات الفروع ظاهرة","reports.exports":"الصادرات المتاحة","reports.exportsIntro":"ملفات CSV بترميز UTF-8 تفتح في Excel أو LibreOffice","reports.register":"سجل طلبات الشراء","reports.platformExport":"الشركات والفروع والحالات والكميات وإجماليات العميل وتكاليف الشراء الداخلية وهامش المنصة.","reports.companyExport":"الفروع والبنود وحالة الاعتماد والتنفيذ والإجماليات المسموحة لحسابك.","reports.download":"تنزيل requests.csv","reports.scoped":"تصدير بنطاق الشركة","reports.scopedBody":"يحتوي السجل على البيانات المتاحة لحسابك فقط.","reports.rule":"قاعدة التسوية","reports.ruleIntro":"تحقق قبل المشاركة","reports.platformRule":"سو الإجماليات مع بنود الطلب.","reports.companyRule":"الاعتماد يضبط الإنفاق الملتزم.","reports.platformRuleBody":"تشمل المبيعات والتكلفة الكميات وتستبعد الملغي، وتظهر رسوم التسليم منفصلة.","reports.companyRuleBody":"تشمل القيمة الطلبات غير الملغاة ويشمل المعتمد ما قبله معتمد الشركة وتحسب الميزانية للشهر الحالي.",
  "audit.eyebrow":"المساءلة","audit.title":"سجل التدقيق","audit.description":"عرض للقراءة فقط للتغييرات المهمة ومن نفذها والسبب المسجل.","audit.recent":"التغييرات الأخيرة","audit.count":"أحدث 500 سجل","audit.when":"الوقت","audit.entity":"الكيان","audit.action":"الإجراء","audit.record":"السجل","audit.user":"المستخدم","audit.reason":"السبب","audit.empty":"لم تسجل تغييرات تدقيق بعد.",
  "settings.eyebrow":"ضبط النظام","settings.title":"الإعدادات والأمان","settings.description":"راجع الإعدادات التي تضبط مساحة عمل أكسورا.","settings.workspaceConfig":"إعداد مساحة العمل","settings.defaults":"الإعدادات التشغيلية الحالية","settings.workspace":"مساحة العمل","settings.platform":"منصة أكسورا","settings.assigned":"الشركة المعينة","settings.timezone":"المنطقة الزمنية","settings.timezoneValue":"توقيت ماليزيا · Asia/Kuala_Lumpur (UTC+8)","settings.currency":"العملة","settings.currencyValue":"الرينغيت الماليزي (MYR)","settings.protection":"الوصول وحماية البيانات","settings.protectionIntro":"قواعد الأمان المطبقة","settings.isolation":"عزل الشركات","settings.isolationBody":"يرى المستخدم سجلات شركته فقط ويمكن للمالك إدارة كل الشركات.","settings.permissions":"صلاحيات الدور والفرع","settings.permissionsBody":"يقدم الطالب الطلب ويقرر المعتمد ويدير مدير الفرع موقعاً ومدير الشركة مساحة العميل.","settings.accounts":"حسابات محمية","settings.accountsBody":"لا يمكن تعطيل المالك والمستخدم الحالي وآخر مدير للشركة بطريق الخطأ.","settings.documents":"حدود المستندات","settings.documentsBody":"حد المرفقات 2 ميغابايت ودليل المورد والتسليم 5 ميغابايت ويتحقق الخادم من الأنواع.","settings.pricing":"إعداد تسعير الطلب","settings.pricingIntro":"حدد الرسوم المقدرة قبل اعتماد الشركة.","settings.snapshot":"تثبت الرسوم عند إرسال الطلب.","settings.tax":"نسبة الضريبة / SST","settings.taxHelp":"استخدم 0 عند عدم انطباق الضريبة.","settings.fee":"رسم التسليم المقدر (ر.م)","settings.feeHelp":"يؤكد الرسم النهائي أثناء التنفيذ.","settings.savePricing":"حفظ التسعير","settings.noCompany":"لا توجد شركة متاحة.","settings.noCompanyBody":"أنشئ أو فعّل شركة قبل إعداد التسعير.","settings.mode":"وضع التنفيذ الحالي","settings.modeIntro":"تشخيص بيئة للقراءة فقط","settings.local":"وضع عينة محلي","settings.production":"وضع إنتاج أكسورا","settings.localBody":"تحفظ السجلات في الذاكرة وتصفّر عند إعادة تشغيل الخادم المحلي.","settings.productionBody":"تحفظ السجلات في PostgreSQL وتستمر التغييرات وتطبق ضوابط الشركات.",
  "help.roleGuide":"دليل دورك","help.complete":"اكتمل الدليل","help.continue":"تابع من حيث توقفت","help.progress":"اكتملت أو تُخطيت {settled} من {total} خطوات منفردة، وتبقى المتخطاة متاحة.","help.progressLabel":"انتهت {settled} من {total} خطوات","help.review":"مراجعة الدليل","help.continueButton":"متابعة الدليل","help.ownerEyebrow":"دليل مالك المنصة","help.ownerTitle":"كيف تعمل أكسورا","help.ownerDescription":"تملك أكسورا الكتالوج العام وتهيئة الشركات والشراء والتسليم للطلبات التي تعتمدها الشركات وتدفعها.","help.ownerManuals":"أدلة المالك المصورة","help.companyEyebrow":"دليل مستخدم الشركة","help.companyTitle":"كيف تشتري شركتك عبر أكسورا","help.companyDescription":"تدير شركتك الأشخاص والفروع والميزانيات والطلبات والاعتمادات والدفع، وتدير أكسورا المنتجات وتجهيز الطلب والتنفيذ والتسليم.","help.companyManuals":"أدلة الشركة المصورة","help.manualsIntro":"افتح الدليل خطوة بخطوة بالإنجليزية أو العربية.","help.englishPdf":"English PDF","help.arabicPdf":"العربية PDF","help.ownerWorkflow":"مسار المالك","help.ownerWorkflowIntro":"هيئ مرة ثم نفذ الطلب المعتمد","help.ownerRules":"قواعد المالك","help.ownerRulesIntro":"احم ثقة العميل والدليل التشغيلي","help.companyWorkflow":"مسار الشركة","help.companyWorkflowIntro":"حدد المسؤولية قبل أول طلب","help.companyRules":"قواعد الشركة","help.companyRulesIntro":"حافظ على شراء مضبوط وقابل للتدقيق",
  "access.eyebrow":"التحكم بالوصول","access.title":"هذه الصفحة ليست ضمن دورك","access.description":"حسابك مسجل الدخول لكنه لا يملك صلاحية هذه المساحة.","access.none":"لم تعرض أي بيانات","access.body":"استخدم التنقل المتاح لدورك واسأل مدير الشركة إذا تغيرت مسؤولياتك.","access.dashboard":"العودة إلى اللوحة","access.settings":"فتح الإعدادات","access.help":"فتح المساعدة",
  "notifications.eyebrow":"المساحة الشخصية","notifications.title":"الإشعارات","notifications.description":"شاهد تحديثات دورك واضبط وصول الأحداث المعتادة.","notifications.history":"سجل الإشعارات","notifications.inbox":"صندوق النشاط","notifications.unread":"{count} تحديثات غير مقروءة","notifications.current":"أنت على اطلاع","notifications.markAll":"تعليم الكل مقروءاً","notifications.marking":"جارٍ الحفظ…","notifications.open":"فتح السجل","notifications.mark":"تعليم كمقروء","notifications.empty":"لا توجد إشعارات بعد","notifications.emptyBody":"ستظهر المهام والقرارات والتسليم والاستلام واستثناءات المالية هنا.","notifications.preferences":"تفضيلات التسليم","notifications.preferencesIntro":"قد ترسل رسائل الحساب والأمان المهمة عند الحاجة.","notifications.inApp":"داخل التطبيق","notifications.email":"البريد","notifications.schedule":"جدول إرسال البريد","notifications.immediate":"فوراً","notifications.daily":"نافذة الإرسال اليومية التالية","notifications.weekly":"نافذة الإرسال الأسبوعية التالية","notifications.safety":"تبقى تحديثات التأخير رسائل منفصلة ولا تحتوي المواضيع على كلمات مرور أو رموز إعداد أو تفاصيل شراء سرية.","notifications.readSaved":"عُلّم الإشعار كمقروء.","notifications.allReadSaved":"عُلّمت كل الإشعارات كمقروءة.","notifications.preferenceSaved":"حُفظ تفضيل التسليم.",
};

const ms: Dictionary = {
  ...en,
  "common.activate":"Aktifkan","common.deactivate":"Nyahaktifkan","common.status":"Status","common.action":"Tindakan","common.save":"Simpan","common.select":"Pilih","common.upload":"Muat naik","common.days":"{count} hari","common.day":"{count} hari","common.readOnly":"Baca sahaja","common.systemMigration":"Sistem / migrasi","common.notSet":"Belum ditetapkan","settings.updated":"Tetapan harga disimpan.",
  "companies.eyebrow":"Data induk Axora","companies.title":"Syarikat pelanggan","companies.description":"Pemilik Axora meluluskan setiap syarikat sebelum cawangan, pengguna dan permintaan pembelian diurus.","companies.register":"Daftar syarikat","companies.count":"{count} rekod syarikat pelanggan","companies.code":"Kod","companies.company":"Syarikat","companies.industry":"Industri","companies.contact":"Hubungan utama","companies.terms":"Terma bayaran","companies.replaceLogo":"Ganti logo","companies.newLogo":"Logo diluluskan baharu untuk {name}","companies.regenerate":"Jana semula tema","companies.createTitle":"Daftar syarikat pelanggan","companies.createIntro":"Axora menjana kod stabil dan tema mudah akses daripada logo diluluskan.","companies.name":"Nama syarikat","companies.billingCycle":"Kitaran bil","companies.monthly":"Bulanan","companies.perOrder":"Setiap pesanan","companies.weekly":"Mingguan","companies.info":"Maklumat syarikat","companies.website":"URL laman web (pilihan)","companies.logo":"Logo syarikat diluluskan","companies.logoHelp":"PNG, JPEG atau WebP sehingga 2 MB. Axora menjana warna portal selamat; pengguna syarikat tidak boleh mengubahnya.","companies.mainName":"Hubungan utama","companies.mainEmail":"E-mel utama","companies.mainPhone":"Telefon utama","companies.billingName":"Hubungan bil","companies.billingEmail":"E-mel bil","companies.billingPhone":"Telefon bil","companies.billingAddress":"Alamat bil","companies.notes":"Nota","companies.submit":"Daftar syarikat",
  "deliveries.eyebrow":"Penyelarasan penghantaran","deliveries.title":"Penghantaran","deliveries.manageDescription":"Cipta tugasan boleh jejak, tugaskan pemandu dan pantau bukti. Penerima pelanggan mengesahkan kuantiti berasingan.","deliveries.viewDescription":"Jejak kemajuan dan bukti pelanggan untuk permintaan yang dibenarkan.","deliveries.create":"Cipta tugasan penghantaran","deliveries.createIntro":"Axora merakam alamat cawangan diluluskan dan menambah baki baris. Tugasan bukan penerimaan pelanggan.","deliveries.request":"Permintaan diluluskan dan dibayar","deliveries.selectRequest":"Pilih permintaan","deliveries.starts":"Tetingkap bermula","deliveries.ends":"Tetingkap tamat","deliveries.instructions":"Arahan pemandu","deliveries.instructionsPlaceholder":"Akses, hubungan diluluskan dan keperluan pengendalian","deliveries.submit":"Cipta tugasan","deliveries.jobs":"Tugasan penghantaran","deliveries.count":"{count} tugasan boleh jejak","deliveries.jobRequest":"Tugasan / permintaan","deliveries.destination":"Destinasi","deliveries.packages":"Bungkusan","deliveries.window":"Tetingkap","deliveries.driver":"Pemandu","deliveries.to":"hingga {date}","deliveries.chooseDriver":"Pilih pemandu","deliveries.assign":"Tugaskan","deliveries.history":"Sejarah penghantaran","deliveries.historyIntro":"Rekod operasi ialah bukti; penerimaan akhir milik penerima pelanggan.","deliveries.requestLine":"Baris permintaan","deliveries.companyProduct":"Syarikat / produk","deliveries.expected":"Dijangka","deliveries.actual":"Sebenar","deliveries.evidenceQuantity":"Kuantiti bukti","deliveries.evidenceIssue":"Bukti / isu",
  "finance.platformEyebrow":"Kawalan kewangan","finance.companyEyebrow":"Bil syarikat","finance.platformTitle":"Invois dan bayaran","finance.companyTitle":"Invois dan resit bayaran anda","finance.platformDescription":"Axora merekod bukti bayaran dan invois untuk rekonsiliasi, bukan memproses bayaran dalam talian.","finance.companyDescription":"Semak invois pelanggan dan rekod bayaran yang direkodkan Axora.","finance.invoiceRegister":"Daftar invois","finance.invoiceCount":"{count} invois","finance.invoice":"Invois","finance.directionRequest":"Arah / permintaan","finance.counterparty":"Pihak lawan","finance.dateDue":"Tarikh / matang","finance.amount":"Amaun","finance.paid":"Dibayar","finance.outstanding":"Belum dibayar","finance.request":"Permintaan","finance.customer":"Pelanggan","finance.supplier":"Pembekal","finance.due":"Matang {date}","finance.paymentRegister":"Daftar bayaran","finance.paymentIntro":"Rujukan bukti untuk rekonsiliasi","finance.date":"Tarikh","finance.reference":"Rujukan","finance.recordedBy":"Direkod oleh",
  "reports.platformEyebrow":"Pelaporan pengurusan Axora","reports.companyEyebrow":"Laporan pembelian syarikat","reports.title":"Laporan dan rekonsiliasi","reports.platformDescription":"Eksport rekod permintaan dan padankan jualan, kos belian dalaman serta margin dengan baris permintaan.","reports.companyDescription":"Semak nilai diminta dan diluluskan, bajet cawangan serta rekod pembelian.","reports.sales":"Jualan pelanggan","reports.salesNote":"Baris tidak dibatalkan","reports.cost":"Kos belian dalaman","reports.costNote":"Kos dalaman mengikut kuantiti","reports.margin":"Margin kasar","reports.fees":"Fi penghantaran","reports.feesNote":"Dilapor berasingan","reports.requested":"Nilai diminta","reports.requestedNote":"Anggaran tanpa permintaan dibatalkan","reports.approved":"Perbelanjaan diluluskan","reports.approvedNote":"Diterima pelulus syarikat","reports.pending":"Kelulusan menunggu","reports.pendingNote":"Menunggu keputusan dibenarkan","reports.remaining":"Baki bajet","reports.budgetCount":"{count} bajet cawangan kelihatan dikonfigurasi","reports.exports":"Eksport tersedia","reports.exportsIntro":"Fail CSV UTF-8 dibuka dalam Excel atau LibreOffice","reports.register":"Daftar permintaan pembelian","reports.platformExport":"Syarikat, cawangan, status, kuantiti, jumlah pelanggan, kos belian dalaman dan margin platform.","reports.companyExport":"Cawangan, item, kelulusan, pemenuhan dan jumlah yang boleh dicapai akaun anda.","reports.download":"Muat turun requests.csv","reports.scoped":"Eksport berskop syarikat","reports.scopedBody":"Daftar hanya mengandungi rekod tersedia untuk akaun anda.","reports.rule":"Peraturan rekonsiliasi","reports.ruleIntro":"Semak sebelum berkongsi","reports.platformRule":"Rekonsiliasi jumlah dengan baris permintaan.","reports.companyRule":"Kelulusan mengawal perbelanjaan komited.","reports.platformRuleBody":"Jualan dan kos merangkumi kuantiti dan mengecualikan batal. Fi penghantaran berasingan.","reports.companyRuleBody":"Nilai diminta merangkumi tidak batal; perbelanjaan diluluskan hanya diterima pelulus dan baki bajet bagi bulan semasa.",
  "audit.eyebrow":"Kebertanggungjawaban","audit.title":"Sejarah audit","audit.description":"Paparan baca sahaja perubahan penting, pelaku dan sebab direkodkan.","audit.recent":"Perubahan terkini","audit.count":"Sehingga 500 rekod terbaru","audit.when":"Bila","audit.entity":"Entiti","audit.action":"Tindakan","audit.record":"Rekod","audit.user":"Pengguna","audit.reason":"Sebab","audit.empty":"Tiada perubahan audit direkodkan.",
  "settings.eyebrow":"Kawalan sistem","settings.title":"Tetapan dan keselamatan","settings.description":"Semak konfigurasi ruang kerja Axora.","settings.workspaceConfig":"Konfigurasi ruang kerja","settings.defaults":"Tetapan operasi semasa","settings.workspace":"Ruang kerja","settings.platform":"Platform Axora","settings.assigned":"Syarikat ditugaskan","settings.timezone":"Zon waktu","settings.timezoneValue":"Waktu Malaysia · Asia/Kuala_Lumpur (UTC+8)","settings.currency":"Mata wang","settings.currencyValue":"Ringgit Malaysia (MYR)","settings.protection":"Akses dan perlindungan data","settings.protectionIntro":"Peraturan keselamatan dikuatkuasakan","settings.isolation":"Pengasingan syarikat","settings.isolationBody":"Pengguna hanya mencapai rekod syarikat ditugaskan; pemilik platform mentadbir semua syarikat.","settings.permissions":"Kebenaran peranan dan cawangan","settings.permissionsBody":"Pemohon menghantar, pelulus memutuskan, pentadbir cawangan mengurus satu lokasi dan pentadbir syarikat mengurus ruang pelanggan.","settings.accounts":"Akaun dilindungi","settings.accountsBody":"Pemilik, pengguna semasa dan pentadbir terakhir syarikat tidak boleh dinyahaktif secara tidak sengaja.","settings.documents":"Had dokumen","settings.documentsBody":"Lampiran perniagaan 2 MB; bukti pembekal dan penghantaran 5 MB. Jenis disahkan pelayan.","settings.pricing":"Konfigurasi harga permintaan","settings.pricingIntro":"Tetapkan caj anggaran sebelum kelulusan syarikat.","settings.snapshot":"Caj dirakam ketika permintaan dihantar.","settings.tax":"Kadar cukai / SST","settings.taxHelp":"Gunakan 0 jika cukai tidak terpakai.","settings.fee":"Anggaran fi penghantaran (RM)","settings.feeHelp":"Fi akhir disahkan semasa pemenuhan.","settings.savePricing":"Simpan tetapan harga","settings.noCompany":"Tiada syarikat tersedia.","settings.noCompanyBody":"Cipta atau aktifkan syarikat sebelum menetapkan harga.","settings.mode":"Mod pelaksanaan semasa","settings.modeIntro":"Diagnostik persekitaran baca sahaja","settings.local":"Mod contoh setempat","settings.production":"Mod produksi Axora","settings.localBody":"Rekod contoh disimpan dalam memori dan ditetap semula apabila pelayan setempat bermula semula.","settings.productionBody":"Rekod disimpan dalam PostgreSQL. Perubahan kekal dan kawalan akses aktif.",
  "help.roleGuide":"Panduan peranan anda","help.complete":"Tutorial selesai","help.continue":"Sambung dari tempat anda berhenti","help.progress":"{settled} daripada {total} langkah selesai atau dilangkau sendiri. Langkah dilangkau kekal tersedia.","help.progressLabel":"{settled} daripada {total} langkah tutorial selesai","help.review":"Semak tutorial","help.continueButton":"Sambung tutorial","help.ownerEyebrow":"Panduan pemilik platform","help.ownerTitle":"Cara Axora beroperasi","help.ownerDescription":"Axora mengurus katalog global, pendaftaran syarikat, pembelian dan penghantaran bagi permintaan yang diluluskan dan dibayar pelanggan.","help.ownerManuals":"Manual pemilik berilustrasi","help.companyEyebrow":"Panduan pengguna syarikat","help.companyTitle":"Cara syarikat anda membeli melalui Axora","help.companyDescription":"Syarikat mengawal orang, cawangan, bajet, permintaan, kelulusan dan Bayar; Axora mengawal produk, penyediaan pesanan dan penghantaran.","help.companyManuals":"Manual syarikat berilustrasi","help.manualsIntro":"Buka panduan langkah demi langkah dalam bahasa Inggeris atau Arab.","help.englishPdf":"English PDF","help.arabicPdf":"العربية PDF","help.ownerWorkflow":"Aliran pemilik","help.ownerWorkflowIntro":"Sediakan sekali, kemudian penuhi permintaan diluluskan","help.ownerRules":"Peraturan pemilik","help.ownerRulesIntro":"Lindungi kepercayaan pelanggan dan bukti operasi","help.companyWorkflow":"Aliran syarikat","help.companyWorkflowIntro":"Tetapkan tanggungjawab sebelum permintaan pertama","help.companyRules":"Peraturan syarikat","help.companyRulesIntro":"Pastikan pembelian terkawal dan boleh diaudit",
  "access.eyebrow":"Kawalan akses","access.title":"Halaman ini bukan sebahagian peranan anda","access.description":"Akaun anda telah log masuk tetapi tiada kebenaran membuka ruang ini.","access.none":"Tiada data dipaparkan","access.body":"Gunakan navigasi untuk peranan anda. Tanya pentadbir syarikat jika tanggungjawab berubah.","access.dashboard":"Kembali ke papan pemuka","access.settings":"Buka tetapan","access.help":"Buka bantuan",
  "notifications.eyebrow":"Ruang peribadi","notifications.title":"Pemberitahuan","notifications.description":"Lihat kemas kini berkaitan peranan dan laraskan cara peristiwa rutin sampai kepada anda.","notifications.history":"Sejarah pemberitahuan","notifications.inbox":"Peti masuk aktiviti","notifications.unread":"{count} kemas kini belum dibaca","notifications.current":"Anda terkini","notifications.markAll":"Tandakan semua dibaca","notifications.marking":"Menyimpan…","notifications.open":"Buka rekod","notifications.mark":"Tandakan dibaca","notifications.empty":"Belum ada pemberitahuan","notifications.emptyBody":"Tugasan, keputusan, penghantaran, penerimaan dan pengecualian kewangan muncul di sini.","notifications.preferences":"Pilihan penghantaran","notifications.preferencesIntro":"Mesej akaun dan keselamatan penting masih boleh dihantar apabila perlu.","notifications.inApp":"Dalam aplikasi","notifications.email":"E-mel","notifications.schedule":"Jadual penghantaran e-mel","notifications.immediate":"Serta-merta","notifications.daily":"Tetingkap harian seterusnya","notifications.weekly":"Tetingkap mingguan seterusnya","notifications.safety":"Kemas kini lewat kekal sebagai e-mel berasingan. Subjek tidak mengandungi kata laluan, token persediaan atau butiran sulit.","notifications.readSaved":"Pemberitahuan ditandakan dibaca.","notifications.allReadSaved":"Semua pemberitahuan ditandakan dibaca.","notifications.preferenceSaved":"Pilihan penghantaran disimpan.",
};

const dictionaries: Record<SupportedLocale, Dictionary> = { en, ar, ms };

export type OperationalMessageKey = keyof typeof en;

export function operationalMessage(locale: SupportedLocale, key: OperationalMessageKey, values: Record<string, string | number> = {}) {
  const template = dictionaries[locale][key] ?? en[key];
  return Object.entries(values).reduce((result, [name, value]) => result.replaceAll(`{${name}}`, String(value)), template);
}

const statuses: Record<SupportedLocale, Record<string, string>> = {
  en: {},
  ar: { Active:"نشط", Inactive:"غير نشط", Selected:"مختار", Approved:"معتمد", Pending:"معلق", Issued:"صادرة", Paid:"مدفوعة", Unpaid:"غير مدفوعة", Matched:"مطابق", EXCEPTION:"استثناء", NOT_READY:"غير جاهز", MATCHED:"مطابق", Delivered:"مُسلّم", Delayed:"متأخر", Cancelled:"ملغي", Failed:"فشل", Assigned:"مسند", Accepted:"مقبول" },
  ms: { Active:"Aktif", Inactive:"Tidak aktif", Selected:"Dipilih", Approved:"Diluluskan", Pending:"Menunggu", Issued:"Dikeluarkan", Paid:"Dibayar", Unpaid:"Belum dibayar", Matched:"Sepadan", EXCEPTION:"Pengecualian", NOT_READY:"Belum sedia", MATCHED:"Sepadan", Delivered:"Dihantar", Delayed:"Lewat", Cancelled:"Dibatalkan", Failed:"Gagal", Assigned:"Ditugaskan", Accepted:"Diterima" },
};

export function operationalStatus(locale: SupportedLocale, status: string) {
  return statuses[locale][status] ?? status.replaceAll("_", " ");
}

export function operationalNumber(locale: SupportedLocale, value: number, options?: Intl.NumberFormatOptions) {
  return new Intl.NumberFormat(locale === "ar" ? "ar-MY" : locale === "ms" ? "ms-MY" : "en-MY", options).format(value);
}

export const notificationEventKeys = ["invitation.sent","invitation.accepted","company.lead.created","company.lead.submitted","company.lead.assigned","company.lead.reassigned","company.lead.contacted","company.lead.information_requested","company.lead.qualified","company.lead.duplicate_cleared","company.lead.duplicate_confirmed","company.lead.note_added","company.lead.task_added","company.lead.task_completed","company.lead.converted","company.lead.rejected","company.lead.archived","company.lead.anonymized","company.lead.sla_overdue","company.onboarding.updated","company.onboarding.ready","company.onboarding.verified","company.verification.submitted","company.verification.approved","company.verification.changes_requested","company.verification.rejected","company.assigned","company.reassigned","company.information_requested","company.administrator_activated","company.activated","company.suspended","request.submitted","approval.needed","request.approved","request.rejected","quotation.requested","quotation.received","supplier.selected","supplier.order_selected","supplier.rfq_acknowledged","supplier.order_acknowledged","delivery.scheduled","delivery.updated","driver.assigned","driver.assignment_rejected","delivery.accepted","delivery.arrived","delivery.attempted","delivery.partially_delivered","delivery.issue_reported","delivery.note_added","delivery.delayed","delivery.completed","receipt.required","discrepancy.opened","invoice.issued","payment.status_changed","order.confirmed","preparation.started","delivery.out_for_delivery","delivery.evidence_recorded","delivery.partial_evidence_recorded","delivery.failed","receipt.confirmed","three_way_match.completed","three_way_match.exception","request.completed","request.cancelled","request.on_hold"] as const;

const eventLabels: Record<SupportedLocale, Record<string, string>> = {
  en: Object.fromEntries(notificationEventKeys.map((key) => [key, key.replaceAll(".", " ").replaceAll("_", " ")])),
  ar: { "invitation.sent":"أرسلت الدعوة","invitation.accepted":"قُبلت الدعوة","request.submitted":"أرسل الطلب","approval.needed":"اعتماد مطلوب","request.approved":"اعتمد الطلب","request.rejected":"رُفض الطلب","quotation.requested":"طلب عرض سعر","quotation.received":"استلم عرض سعر","supplier.selected":"اختير المورد","delivery.scheduled":"جُدول التسليم","delivery.updated":"تم تحديث التسليم","driver.assigned":"أُسند السائق","driver.assignment_rejected":"رفض السائق المهمة","delivery.accepted":"قبل السائق التسليم","delivery.arrived":"وصل السائق","delivery.attempted":"جرت محاولة التسليم","delivery.partially_delivered":"تم التسليم جزئيًا","delivery.issue_reported":"أُبلغ عن مشكلة تسليم","delivery.note_added":"أضاف السائق ملاحظة","delivery.delayed":"تأخر التسليم","delivery.completed":"اكتمل التسليم","receipt.required":"تأكيد الاستلام مطلوب","discrepancy.opened":"فُتح اختلاف","invoice.issued":"أصدرت الفاتورة","payment.status_changed":"تغيرت حالة الدفع","order.confirmed":"تأكد الأمر","preparation.started":"بدأ التجهيز","delivery.out_for_delivery":"خرج للتسليم","delivery.evidence_recorded":"سُجل دليل التسليم","delivery.partial_evidence_recorded":"دليل تسليم جزئي","delivery.failed":"فشل التسليم","receipt.confirmed":"تأكد الاستلام","three_way_match.completed":"اكتملت المطابقة الثلاثية","three_way_match.exception":"استثناء مطابقة ثلاثية","request.completed":"اكتمل الطلب","request.cancelled":"أُلغي الطلب","request.on_hold":"الطلب معلق" },
  ms: { "invitation.sent":"Jemputan dihantar","invitation.accepted":"Jemputan diterima","request.submitted":"Permintaan dihantar","approval.needed":"Kelulusan diperlukan","request.approved":"Permintaan diluluskan","request.rejected":"Permintaan ditolak","quotation.requested":"Sebut harga diminta","quotation.received":"Sebut harga diterima","supplier.selected":"Pembekal dipilih","delivery.scheduled":"Penghantaran dijadualkan","delivery.updated":"Penghantaran dikemas kini","driver.assigned":"Pemandu ditugaskan","driver.assignment_rejected":"Pemandu menolak tugasan","delivery.accepted":"Pemandu menerima penghantaran","delivery.arrived":"Pemandu tiba","delivery.attempted":"Penghantaran dicuba","delivery.partially_delivered":"Dihantar sebahagian","delivery.issue_reported":"Isu penghantaran dilaporkan","delivery.note_added":"Nota pemandu ditambah","delivery.delayed":"Penghantaran lewat","delivery.completed":"Penghantaran selesai","receipt.required":"Pengesahan penerimaan diperlukan","discrepancy.opened":"Percanggahan dibuka","invoice.issued":"Invois dikeluarkan","payment.status_changed":"Status bayaran berubah","order.confirmed":"Pesanan disahkan","preparation.started":"Penyediaan bermula","delivery.out_for_delivery":"Keluar untuk penghantaran","delivery.evidence_recorded":"Bukti penghantaran direkod","delivery.partial_evidence_recorded":"Bukti penghantaran separa","delivery.failed":"Penghantaran gagal","receipt.confirmed":"Penerimaan disahkan","three_way_match.completed":"Padanan tiga hala selesai","three_way_match.exception":"Pengecualian padanan tiga hala","request.completed":"Permintaan selesai","request.cancelled":"Permintaan dibatalkan","request.on_hold":"Permintaan ditahan" },
};

export function operationalEventLabel(locale: SupportedLocale, eventKey: string) {
  const legacyLabels: Record<SupportedLocale, Record<string, string>> = {
    en: {
      "quotation.requested": "Legacy processing started",
      "quotation.received": "Legacy quotation recorded",
      "supplier.selected": "Legacy selection recorded",
      "supplier.order_selected": "Legacy order selection recorded",
      "supplier.rfq_acknowledged": "Legacy request acknowledged",
      "supplier.order_acknowledged": "Legacy order acknowledged",
    },
    ar: {
      "quotation.requested": "بدأت معالجة سابقة",
      "quotation.received": "سُجل عرض سابق",
      "supplier.selected": "سُجل اختيار سابق",
      "supplier.order_selected": "سُجل طلب سابق",
      "supplier.rfq_acknowledged": "تم تأكيد طلب سابق",
      "supplier.order_acknowledged": "تم تأكيد أمر سابق",
    },
    ms: {
      "quotation.requested": "Pemprosesan terdahulu bermula",
      "quotation.received": "Sebut harga terdahulu direkod",
      "supplier.selected": "Pilihan terdahulu direkod",
      "supplier.order_selected": "Pilihan pesanan terdahulu direkod",
      "supplier.rfq_acknowledged": "Permintaan terdahulu diakui",
      "supplier.order_acknowledged": "Pesanan terdahulu diakui",
    },
  };
  if (legacyLabels[locale][eventKey]) return legacyLabels[locale][eventKey];
  if (locale === "en") return eventKey.split(/[._]/).map((part, index) => index ? part : part[0]?.toUpperCase() + part.slice(1)).join(" ");
  const supplierEvents: Record<"ar" | "ms", Record<string, string>> = {
    ar: {
      "company.lead.created": "أُنشئ عميل محتمل جديد",
      "company.lead.submitted": "استُلم استفسار شركة جديد",
      "company.lead.assigned": "أُسند العميل المحتمل",
      "company.lead.reassigned": "أُعيد إسناد العميل المحتمل",
      "company.lead.contacted": "تم التواصل مع العميل المحتمل",
      "company.lead.information_requested": "طُلبت معلومات العميل المحتمل",
      "company.lead.qualified": "تأهل العميل المحتمل",
      "company.lead.duplicate_cleared": "تم استبعاد تكرار العميل المحتمل",
      "company.lead.duplicate_confirmed": "تأكد تكرار العميل المحتمل",
      "company.lead.note_added": "أُضيفت ملاحظة للعميل المحتمل",
      "company.lead.task_added": "أُضيفت مهمة للعميل المحتمل",
      "company.lead.task_completed": "اكتملت مهمة العميل المحتمل",
      "company.lead.converted": "حُوّل العميل المحتمل إلى شركة",
      "company.lead.rejected": "رُفض العميل المحتمل",
      "company.lead.archived": "أُرشف العميل المحتمل",
      "company.lead.anonymized": "أُخفيت هوية العميل المحتمل",
      "company.lead.sla_overdue": "تأخرت متابعة العميل المحتمل",
      "company.onboarding.updated": "حُفظ إعداد الشركة",
      "company.onboarding.ready": "اكتمل إعداد الشركة للمراجعة",
      "company.onboarding.verified": "تم التحقق من إعداد الشركة",
      "company.verification.submitted": "أُرسل ملف الشركة للتحقق",
      "company.verification.approved": "تم التحقق من الشركة",
      "company.verification.changes_requested": "طُلبت تغييرات على الشركة",
      "company.verification.rejected": "رُفض ملف الشركة",
      "company.assigned": "أُسندت الشركة",
      "company.reassigned": "أُعيد إسناد الشركة",
      "company.information_requested": "طُلبت معلومات الشركة",
      "company.administrator_activated": "تم تفعيل مدير الشركة",
      "company.activated": "تم تفعيل الشركة",
      "company.suspended": "تم تعليق الشركة",
      "supplier.rfq_acknowledged": "أكد المورد طلب عرض السعر",
      "supplier.order_acknowledged": "أكد المورد الطلب المختار",
      "supplier.order_selected": "تم اختيار طلب المورد",
    },
    ms: {
      "company.lead.created": "Prospek syarikat dicipta",
      "company.lead.submitted": "Pertanyaan syarikat diterima",
      "company.lead.assigned": "Prospek syarikat ditugaskan",
      "company.lead.reassigned": "Prospek syarikat ditugaskan semula",
      "company.lead.contacted": "Prospek syarikat telah dihubungi",
      "company.lead.information_requested": "Maklumat prospek syarikat diminta",
      "company.lead.qualified": "Prospek syarikat layak",
      "company.lead.duplicate_cleared": "Padanan pendua prospek diketepikan",
      "company.lead.duplicate_confirmed": "Pendua prospek disahkan",
      "company.lead.note_added": "Nota prospek ditambah",
      "company.lead.task_added": "Tugasan prospek ditambah",
      "company.lead.task_completed": "Tugasan prospek selesai",
      "company.lead.converted": "Prospek ditukar kepada syarikat",
      "company.lead.rejected": "Prospek syarikat ditolak",
      "company.lead.archived": "Prospek syarikat diarkibkan",
      "company.lead.anonymized": "Data prospek syarikat dianonimkan",
      "company.lead.sla_overdue": "Susulan prospek syarikat lewat",
      "company.onboarding.updated": "Persediaan syarikat disimpan",
      "company.onboarding.ready": "Persediaan syarikat sedia untuk semakan",
      "company.onboarding.verified": "Persediaan syarikat disahkan",
      "company.verification.submitted": "Syarikat dihantar untuk pengesahan",
      "company.verification.approved": "Syarikat disahkan",
      "company.verification.changes_requested": "Perubahan syarikat diminta",
      "company.verification.rejected": "Penyerahan syarikat ditolak",
      "company.assigned": "Syarikat ditugaskan",
      "company.reassigned": "Syarikat ditugaskan semula",
      "company.information_requested": "Maklumat syarikat diminta",
      "company.administrator_activated": "Pentadbir Syarikat diaktifkan",
      "company.activated": "Syarikat diaktifkan",
      "company.suspended": "Syarikat digantung",
      "supplier.rfq_acknowledged": "Pembekal mengakui RFQ",
      "supplier.order_acknowledged": "Pembekal mengakui pesanan terpilih",
      "supplier.order_selected": "Pesanan pembekal dipilih",
    },
  };
  return eventLabels[locale][eventKey]
    ?? (locale === "ar" || locale === "ms" ? supplierEvents[locale][eventKey] : undefined)
    ?? eventKey;
}

export function operationalDictionaryKeys() { return Object.keys(en).sort(); }
export function operationalMissingKeys(locale: SupportedLocale) { return locale === "en" ? [] : Object.keys(en).filter((key) => !dictionaries[locale][key]); }

interface HelpItem { title: string; body: string }
const helpContent: Record<SupportedLocale, { ownerSteps: HelpItem[]; ownerRules: HelpItem[]; companySteps: HelpItem[]; companyRules: HelpItem[] }> = {
  en: {
    ownerSteps: [
      { title: "1. Onboard the company", body: "Create the approved company, first branch, and a scoped Company Administrator invitation." },
      { title: "2. Set up Axora teams", body: "Create HR Management, Agent, and Delivery Guy accounts with the smallest required permissions." },
      { title: "3. Publish catalog products", body: "Add customer price, searchable details, a clear image, and alternative text. Buying cost stays private." },
      { title: "4. Wait for approval and Pay", body: "A company approver authorizes the request against budget, then an authorized customer user selects Pay." },
      { title: "5. Prepare and deliver", body: "Axora prepares the paid request, then a Delivery Guy delivers it and records independent receipt evidence." },
    ],
    ownerRules: [
      { title: "Separation of duties", body: "Customers authorize budget; Axora manages buying, fulfilment and delivery. Platform owners do not approve customer budgets." },
      { title: "One global catalog", body: "Create products once in the global catalog. Deactivate old records instead of deleting history." },
      { title: "Useful product images", body: "Use a validated JPEG, PNG, or WebP image that matches the product and add concise alternative text." },
    ],
    companySteps: [
      { title: "1. Set up branches", body: "The Company Administrator confirms delivery locations and monthly purchasing budgets." },
      { title: "2. Invite named users", body: "Assign the smallest canonical role and correct company or branch scope. Users create their own passwords." },
      { title: "3. Search the Axora Shop", body: "Find products by image, name, code, category, or brand. Axora maintains the global catalog." },
      { title: "4. Submit a purchase request", body: "Choose branch, items, quantities, needed-by date, and business reason from your named account." },
      { title: "5. Approve against budget", body: "A different authorized approver reviews the request and records approval or rejection." },
      { title: "6. Track fulfilment", body: "Follow preparation, delivery status, independent receipt, invoice, payment status, and completion." },
    ],
    companyRules: [
      { title: "Budget belongs to the branch", body: "Only an authorized administrator changes budgets. Approved requests, not drafts, commit the amount." },
      { title: "No self-approval", body: "The requester cannot approve their own request. Assign another approver in the required scope." },
      { title: "Use named accounts", body: "Never share passwords or administrator accounts. Role controls action; scope controls records." },
    ],
  },
  ar: {
    ownerSteps: [
      { title: "1. تهيئة الشركة", body: "أنشئ الشركة والفرع الأول ودعوة مدير شركة بالنطاق الصحيح." },
      { title: "2. إعداد فرق أكسورا", body: "أنشئ حسابات الموارد البشرية والوكلاء ومسؤولي التوصيل بأقل الصلاحيات اللازمة." },
      { title: "3. نشر منتجات الكتالوج", body: "أضف سعر العميل والتفاصيل والصورة والنص البديل وتبقى تكلفة الشراء خاصة." },
      { title: "4. انتظار الاعتماد والدفع", body: "يعتمد مخول من الشركة الطلب مقابل الميزانية ثم يختار مستخدم عميل مخول الدفع." },
      { title: "5. التجهيز والتسليم", body: "تجهز أكسورا الطلب المدفوع ثم يسلمه مسؤول التوصيل ويسجل دليل الاستلام المستقل." },
    ],
    ownerRules: [
      { title: "فصل المهام", body: "يفوض العميل الميزانية وتدير أكسورا الشراء والتنفيذ والتسليم ولا يعتمد المالك ميزانية العميل." },
      { title: "كتالوج عام واحد", body: "أنشئ المنتجات مرة في الكتالوج العام وعطل السجل القديم بدلاً من حذف التاريخ." },
      { title: "صور منتجات مفيدة", body: "استخدم JPEG أو PNG أو WebP متحققاً منه يطابق المنتج مع نص بديل مختصر." },
    ],
    companySteps: [
      { title: "1. إعداد الفروع", body: "يؤكد مدير الشركة مواقع التسليم والميزانيات الشهرية." },
      { title: "2. دعوة مستخدمين مسمين", body: "عين أقل دور قياسي والنطاق الصحيح وينشئ المستخدم كلمة مروره." },
      { title: "3. البحث في متجر أكسورا", body: "ابحث بالصورة أو الاسم أو الرمز أو الفئة أو العلامة وتدير أكسورا الكتالوج العام." },
      { title: "4. إرسال طلب شراء", body: "اختر الفرع والبنود والكميات وتاريخ الحاجة والسبب من حسابك المسمى." },
      { title: "5. الاعتماد مقابل الميزانية", body: "يراجع معتمد مختلف الطلب ويسجل الاعتماد أو الرفض." },
      { title: "6. متابعة التنفيذ", body: "تابع تقدم الشراء ودليل مسؤول التوصيل والاستلام المستقل والفاتورة وحالة الدفع والإكمال." },
    ],
    companyRules: [
      { title: "الميزانية للفرع", body: "يغيرها مدير مخول وتلتزم القيمة بعد الاعتماد لا في المسودة." },
      { title: "لا اعتماد ذاتي", body: "لا يعتمد مقدم الطلب طلبه ويجب تعيين معتمد آخر في النطاق." },
      { title: "حسابات مسماة", body: "لا تشارك كلمات المرور أو حسابات الإدارة؛ يحدد الدور الإجراء والنطاق السجلات." },
    ],
  },
  ms: {
    ownerSteps: [
      { title: "1. Terima masuk syarikat", body: "Cipta syarikat, cawangan pertama dan jemputan Pentadbir Syarikat berskop." },
      { title: "2. Sediakan pasukan Axora", body: "Cipta akaun Pengurusan Sumber Manusia, Ejen dan Delivery Guy dengan kebenaran minimum." },
      { title: "3. Terbit produk katalog", body: "Tambah harga pelanggan, butiran, imej dan teks alternatif; kos belian kekal peribadi." },
      { title: "4. Tunggu kelulusan dan Bayar", body: "Pelulus syarikat meluluskan permintaan terhadap bajet, kemudian pengguna pelanggan dibenarkan memilih Bayar." },
      { title: "5. Sedia dan hantar", body: "Axora menyediakan permintaan berbayar, kemudian Penghantar menghantarnya dan merekod bukti penerimaan bebas." },
    ],
    ownerRules: [
      { title: "Pengasingan tugas", body: "Pelanggan meluluskan bajet; Axora mengurus pembelian, pemenuhan dan penghantaran. Pemilik tidak meluluskan bajet pelanggan." },
      { title: "Satu katalog global", body: "Cipta produk sekali dalam katalog global. Nyahaktif rekod lama dan kekalkan sejarah." },
      { title: "Imej produk berguna", body: "Gunakan JPEG, PNG atau WebP yang disahkan dan sepadan produk dengan teks alternatif." },
    ],
    companySteps: [
      { title: "1. Sediakan cawangan", body: "Pentadbir Syarikat mengesahkan lokasi penghantaran dan bajet bulanan." },
      { title: "2. Jemput pengguna bernama", body: "Tetapkan peranan kanonik minimum dan skop betul; pengguna mencipta kata laluan sendiri." },
      { title: "3. Cari di Kedai Axora", body: "Cari melalui imej, nama, kod, kategori atau jenama. Axora mengurus katalog global." },
      { title: "4. Hantar permintaan", body: "Pilih cawangan, item, kuantiti, tarikh diperlukan dan sebab daripada akaun bernama." },
      { title: "5. Lulus terhadap bajet", body: "Pelulus lain yang dibenarkan menyemak dan merekod kelulusan atau penolakan." },
      { title: "6. Jejak pemenuhan", body: "Ikuti persediaan, status penghantaran, penerimaan bebas, invois, status bayaran dan selesai." },
    ],
    companyRules: [
      { title: "Bajet milik cawangan", body: "Hanya pentadbir dibenarkan mengubah bajet. Permintaan diluluskan, bukan draf, mengikat amaun." },
      { title: "Tiada kelulusan sendiri", body: "Pemohon tidak boleh meluluskan permintaan sendiri. Tetapkan pelulus lain dalam skop." },
      { title: "Gunakan akaun bernama", body: "Jangan kongsi kata laluan atau akaun pentadbir. Peranan mengawal tindakan; skop mengawal rekod." },
    ],
  },
};

export function operationalHelpContent(locale: SupportedLocale) { return helpContent[locale]; }
