import type { SupportedLocale } from "./i18n";

interface ProductEditorMessages {
  eyebrow: string; description: string; back: string; information: string; informationBody: string; save: string;
  slideshow: string; uploadCount: (count: number, max: number) => string; addImages: string; imagesHelp: string;
  uploadAlt: string; altPlaceholder: (name: string) => string; altHelp: string; upload: string; gallery: string; galleryBody: string;
  primary: string; image: (index: number) => string; imageDescription: string; saveDescription: string; makePrimary: string;
  shownFirst: string; remove: string; empty: string; emptyBody: string;
}

const en: ProductEditorMessages = { eyebrow: "Platform owner · Product editor", description: "Update every catalog field and manage the customer-facing image slideshow.", back: "Back to products", information: "Edit product information", informationBody: "Changes appear in the customer catalog after saving.", save: "Save product changes", slideshow: "Image slideshow", uploadCount: (count, max) => `${count} of ${max} images uploaded`, addImages: "Add images", imagesHelp: "Select multiple JPEG, PNG or WebP images. Each original file may be up to 5 MB.", uploadAlt: "Alternative text for this upload", altPlaceholder: (name) => `Example: ${name} shown from the front`, altHelp: "You can edit the description for each image after uploading.", upload: "Upload images", gallery: "Manage gallery", galleryBody: "The primary image appears first. Customers can move through every active image.", primary: "Primary", image: (index) => `Image ${index}`, imageDescription: "Image description", saveDescription: "Save description", makePrimary: "Make primary", shownFirst: "Shown first", remove: "Remove", empty: "No product images yet", emptyBody: "Upload one or more images to create the customer slideshow." };
const ar: ProductEditorMessages = { eyebrow: "مالك المنصة · محرر المنتجات", description: "حدّث كل حقول الكتالوج وأدر عرض الصور الظاهر للعملاء.", back: "العودة إلى المنتجات", information: "تعديل معلومات المنتج", informationBody: "تظهر التغييرات في كتالوج العميل بعد الحفظ.", save: "حفظ تغييرات المنتج", slideshow: "عرض صور المنتج", uploadCount: (count, max) => `تم تحميل ${count} من ${max} صور`, addImages: "إضافة صور", imagesHelp: "اختر عدة صور JPEG أو PNG أو WebP. الحد الأقصى لكل ملف أصلي 5 م.ب.", uploadAlt: "النص البديل لهذا التحميل", altPlaceholder: (name) => `مثال: ${name} كما يظهر من الأمام`, altHelp: "يمكنك تعديل وصف كل صورة بعد التحميل.", upload: "تحميل الصور", gallery: "إدارة المعرض", galleryBody: "تظهر الصورة الأساسية أولاً ويمكن للعملاء التنقل بين كل الصور النشطة.", primary: "أساسية", image: (index) => `الصورة ${index}`, imageDescription: "وصف الصورة", saveDescription: "حفظ الوصف", makePrimary: "جعلها أساسية", shownFirst: "تظهر أولاً", remove: "إزالة", empty: "لا توجد صور للمنتج بعد", emptyBody: "حمّل صورة أو أكثر لإنشاء عرض صور العميل." };
const ms: ProductEditorMessages = { eyebrow: "Pemilik platform · Editor produk", description: "Kemas kini setiap medan katalog dan urus tayangan imej untuk pelanggan.", back: "Kembali ke produk", information: "Edit maklumat produk", informationBody: "Perubahan muncul dalam katalog pelanggan selepas disimpan.", save: "Simpan perubahan produk", slideshow: "Tayangan imej", uploadCount: (count, max) => `${count} daripada ${max} imej dimuat naik`, addImages: "Tambah imej", imagesHelp: "Pilih beberapa imej JPEG, PNG atau WebP. Setiap fail asal boleh sehingga 5 MB.", uploadAlt: "Teks alternatif untuk muat naik ini", altPlaceholder: (name) => `Contoh: ${name} dilihat dari hadapan`, altHelp: "Anda boleh mengedit penerangan setiap imej selepas memuat naik.", upload: "Muat naik imej", gallery: "Urus galeri", galleryBody: "Imej utama muncul dahulu. Pelanggan boleh melihat setiap imej aktif.", primary: "Utama", image: (index) => `Imej ${index}`, imageDescription: "Penerangan imej", saveDescription: "Simpan penerangan", makePrimary: "Jadikan utama", shownFirst: "Ditunjukkan dahulu", remove: "Buang", empty: "Belum ada imej produk", emptyBody: "Muat naik satu atau lebih imej untuk mencipta tayangan pelanggan." };

export const PRODUCT_EDITOR_MESSAGES: Record<SupportedLocale, ProductEditorMessages> = { en, ar, ms };
export function productEditorMessages(locale: SupportedLocale = "en") { return PRODUCT_EDITOR_MESSAGES[locale]; }
