import type { SupportedLocale } from "./i18n";

interface RequestDetailMessages {
  platformEyebrow: string; companyEyebrow: string; itemCount: (count: number) => string;
  grossMargin: string; requestedItems: string; platformItemsBody: string; companyItemsBody: string;
  line: string; item: string; product: string; quantity: string; buyTotal: string; customerTotal: string;
  unitPrice: string; lineTotal: string; delivery: string; notAssigned: string; operationsInfo: string; requestInfo: string;
  operationsBody: string; requestBody: string; noInvoice: string; deliveryFees: string; deliveryFeesBody: string;
  remaining: string; noBudget: string; committedBudget: (committed: string, monthly: string) => string; budgetHelp: string;
  fulfilment: string; fulfilmentBody: string; rejected: string; waitingApproval: string; approvalRequired: string;
  nextStatus: string; updateStatus: string; readOnly: string; closed: string;
  readOnlyBody: string; closedBody: string; companyApproval: string; companyApprovalBody: string; waitingDecision: string;
  approvedBy: (name?: string) => string; companyRejected: string; afterApproval: string; decisionRecorded: string;
  reviewApproval: string; timeline: string; workflowUpdated: string; byActor: (name: string) => string;
  bySystem: string; requestCreated: string; approvalTimeline: (status: string) => string; awaitingApprover: string;
  currentPosition: string; workflow: Record<string, string>;
  readyToPay: string; payBody: (amount: string) => string; pay: string; paid: string;
  downloadInvoice: string; invoicePreparing: string; invoiceEmailStatus: (status: string) => string;
  cancellationTitle: string; cancellationBody: string;
  cancelRequest: string; cancellationComplete: string; cancellationFailed: string;
}

const en: RequestDetailMessages = {
  platformEyebrow: "Axora fulfilment request", companyEyebrow: "Company request", itemCount: (count) => `${count} requested item${count === 1 ? "" : "s"}`,
  grossMargin: "Gross margin", requestedItems: "Requested items", platformItemsBody: "Products, quantities, permitted pricing and delivery status", companyItemsBody: "Catalog items and estimated customer prices submitted for approval", line: "Line", item: "Item", product: "Product", quantity: "Quantity", buyTotal: "Internal line total", customerTotal: "Customer total", unitPrice: "Unit price", lineTotal: "Estimated line total", delivery: "Delivery", notAssigned: "Not assigned", operationsInfo: "Operational information", requestInfo: "Request and budget information", operationsBody: "Customer intake, finance and delivery context", requestBody: "Who requested the items, where they are needed and their approval impact", noInvoice: "No customer invoice yet", deliveryFees: "delivery fees", deliveryFeesBody: "Reported separately from product sales and internal margin.", remaining: "remaining", noBudget: "No monthly budget configured", committedBudget: (committed, monthly) => `${committed} committed from a ${monthly} monthly branch budget.`, budgetHelp: "A company administrator can set this branch’s budget from the Branches page.", fulfilment: "Axora fulfilment", fulfilmentBody: "Axora can begin preparing the order only after the customer company approves this request.", rejected: "The company rejected this request.", waitingApproval: "Waiting for company approval.", approvalRequired: "An authorised company approver must decide before Axora begins preparing the order.", nextStatus: "Allowed next status", updateStatus: "Update fulfilment status", readOnly: "Read-only access", closed: "This workflow is closed.", readOnlyBody: "Your role can view this request but cannot change its fulfilment status.", closedBody: "Completed and cancelled requests are read-only.", companyApproval: "Company approval", companyApprovalBody: "An authorised company approver decides whether this request may use the branch budget.", waitingDecision: "Waiting for a company decision.", approvedBy: (name) => `Approved${name ? ` by ${name}` : ""}.`, companyRejected: "Rejected by the company.", afterApproval: "Axora will start fulfilment only after approval.", decisionRecorded: "The decision is recorded in the request history.", reviewApproval: "Review approval", timeline: "Timeline", workflowUpdated: "Workflow updated", byActor: (name) => ` by ${name}`, bySystem: " by Axora system", requestCreated: "Request created", approvalTimeline: (status) => `Company approval: ${status}`, awaitingApprover: "Awaiting an authorised approver", currentPosition: "Current Axora fulfilment position",
  workflow: { "request.submitted": "Request submitted", "request.approved": "Company approved request", "request.rejected": "Company rejected request", "quotation.requested": "Legacy processing started", "quotation.received": "Legacy quotation recorded", "supplier.selected": "Legacy selection recorded", "order.confirmed": "Order confirmed", "preparation.started": "Preparation started", "preparation.updated": "Order preparation updated", "delivery.updated": "Delivery update recorded", "delivery.scheduled": "Delivery scheduled", "driver.assignment_rejected": "Driver declined assignment", "delivery.accepted": "Driver accepted delivery", "delivery.arrived": "Driver arrived", "delivery.attempted": "Delivery attempted", "delivery.partially_delivered": "Driver reported partial delivery", "delivery.issue_reported": "Driver reported a delivery issue", "delivery.note_added": "Driver note added", "delivery.out_for_delivery": "Out for delivery", "delivery.evidence_recorded": "Driver evidence recorded", "delivery.partial_evidence_recorded": "Partial delivery evidence recorded", "delivery.delayed": "Delivery delayed", "delivery.failed": "Delivery failed", "delivery.completed": "Delivery completed", "receipt.confirmed": "Receipt confirmed", "discrepancy.opened": "Receiving discrepancy raised", "invoice.issued": "Invoice issued", "payment.status_changed": "Payment status updated", "request.completed": "Request completed", "request.cancelled": "Request cancelled", "request.on_hold": "Request placed on hold" },
  readyToPay: "Ready to pay", payBody: (amount) => `The final server-calculated total is ${amount}.`, pay: "Pay", paid: "Paid",
  downloadInvoice: "Download invoice PDF", invoicePreparing: "Your finalized invoice PDF is being prepared.", invoiceEmailStatus: (status) => `Invoice email: ${status.toLowerCase().replaceAll("_", " ")}`,
  cancellationTitle: "Cancel purchase request", cancellationBody: "Cancellation before payment releases the remaining budget reservation. Paid requests cannot be cancelled here.", cancelRequest: "Cancel request", cancellationComplete: "The request was cancelled and its remaining budget reservation was released.", cancellationFailed: "The request could not be cancelled in its current state.",
};

const ar: RequestDetailMessages = {
  ...en, platformEyebrow: "طلب تنفيذ أكسورا", companyEyebrow: "طلب الشركة", itemCount: (count) => `${count} بنود مطلوبة`, grossMargin: "هامش الربح الإجمالي", requestedItems: "البنود المطلوبة", platformItemsBody: "المنتجات والكميات والأسعار المسموح بها وحالة التسليم", companyItemsBody: "بنود الكتالوج وأسعار العميل التقديرية المرسلة للاعتماد", line: "البند", item: "البند", product: "المنتج", quantity: "الكمية", buyTotal: "إجمالي الشراء", customerTotal: "إجمالي العميل", unitPrice: "سعر الوحدة", lineTotal: "إجمالي البند التقديري", delivery: "التسليم", notAssigned: "غير معين", operationsInfo: "المعلومات التشغيلية", requestInfo: "معلومات الطلب والميزانية", operationsBody: "سياق طلب العميل والمالية والتسليم", requestBody: "مقدم الطلب ومكان الحاجة وأثر الاعتماد", noInvoice: "لا توجد فاتورة عميل بعد", deliveryFees: "رسوم التسليم", deliveryFeesBody: "تظهر منفصلة عن مبيعات المنتجات والهامش الداخلي.", remaining: "متبقي", noBudget: "لم تُحدد ميزانية شهرية", committedBudget: (committed, monthly) => `حُجز ${committed} من ميزانية الفرع الشهرية ${monthly}.`, budgetHelp: "يمكن لمدير الشركة تحديد ميزانية الفرع من صفحة الفروع.", fulfilment: "تنفيذ أكسورا", fulfilmentBody: "لا تستطيع أكسورا بدء تجهيز الطلب إلا بعد اعتماد شركة العميل لهذا الطلب.", rejected: "رفضت الشركة هذا الطلب.", waitingApproval: "بانتظار اعتماد الشركة.", approvalRequired: "يجب أن يقرر معتمد مخول من الشركة قبل بدء تجهيز الطلب.", nextStatus: "الحالة التالية المسموحة", updateStatus: "تحديث حالة التنفيذ", readOnly: "صلاحية قراءة فقط", closed: "سير العمل مغلق.", readOnlyBody: "يمكن لدورك عرض الطلب دون تغيير حالته.", closedBody: "الطلبات المكتملة والملغاة للقراءة فقط.", companyApproval: "اعتماد الشركة", companyApprovalBody: "يقرر معتمد مخول ما إذا كان الطلب يستطيع استخدام ميزانية الفرع.", waitingDecision: "بانتظار قرار الشركة.", approvedBy: (name) => `تم الاعتماد${name ? ` بواسطة ${name}` : ""}.`, companyRejected: "رفضته الشركة.", afterApproval: "تبدأ أكسورا التنفيذ بعد الاعتماد فقط.", decisionRecorded: "القرار مسجل في سجل الطلب.", reviewApproval: "مراجعة الاعتماد", timeline: "الخط الزمني", workflowUpdated: "تم تحديث سير العمل", byActor: (name) => ` بواسطة ${name}`, bySystem: " بواسطة نظام أكسورا", requestCreated: "تم إنشاء الطلب", approvalTimeline: (status) => `اعتماد الشركة: ${status}`, awaitingApprover: "بانتظار معتمد مخول", currentPosition: "موضع التنفيذ الحالي لدى أكسورا",
  workflow: { "request.submitted": "تم إرسال الطلب", "request.approved": "اعتمدت الشركة الطلب", "request.rejected": "رفضت الشركة الطلب", "quotation.requested": "بدأت معالجة سابقة", "quotation.received": "سُجل عرض سابق", "supplier.selected": "سُجل اختيار سابق", "order.confirmed": "تم تأكيد الطلب", "preparation.started": "بدأ التحضير", "preparation.updated": "تحدّث تجهيز الطلب", "delivery.updated": "تم تسجيل تحديث للتسليم", "delivery.scheduled": "تمت جدولة التسليم", "driver.assignment_rejected": "رفض السائق المهمة", "delivery.accepted": "قبل السائق مهمة التسليم", "delivery.arrived": "وصل السائق", "delivery.attempted": "جرت محاولة التسليم", "delivery.partially_delivered": "سجل السائق تسليمًا جزئيًا", "delivery.issue_reported": "أبلغ السائق عن مشكلة تسليم", "delivery.note_added": "أضاف السائق ملاحظة", "delivery.out_for_delivery": "خرج للتسليم", "delivery.evidence_recorded": "تم تسجيل دليل السائق", "delivery.partial_evidence_recorded": "تم تسجيل دليل تسليم جزئي", "delivery.delayed": "تأخر التسليم", "delivery.failed": "فشل التسليم", "delivery.completed": "اكتمل التسليم", "receipt.confirmed": "تم تأكيد الاستلام", "discrepancy.opened": "أُبلغ عن اختلاف في الاستلام", "invoice.issued": "صدرت الفاتورة", "payment.status_changed": "تغيرت حالة الدفع", "request.completed": "اكتمل الطلب", "request.cancelled": "أُلغي الطلب", "request.on_hold": "عُلّق الطلب" },
  readyToPay: "جاهز للدفع", payBody: (amount) => `الإجمالي النهائي المحسوب من الخادم هو ${amount}.`, pay: "ادفع", paid: "مدفوع",
  downloadInvoice: "تنزيل الفاتورة PDF", invoicePreparing: "يتم إعداد ملف الفاتورة النهائية.", invoiceEmailStatus: (status) => `بريد الفاتورة: ${status.toLowerCase().replaceAll("_", " ")}`,
  cancellationTitle: "إلغاء طلب الشراء", cancellationBody: "يحرر الإلغاء قبل الدفع حجز الميزانية المتبقي. لا يمكن إلغاء الطلبات المدفوعة هنا.", cancelRequest: "إلغاء الطلب", cancellationComplete: "تم إلغاء الطلب وتحرير حجز الميزانية المتبقي.", cancellationFailed: "لا يمكن إلغاء الطلب في حالته الحالية.",
};

const ms: RequestDetailMessages = {
  ...en, platformEyebrow: "Permintaan pemenuhan Axora", companyEyebrow: "Permintaan syarikat", itemCount: (count) => `${count} item diminta`, grossMargin: "Margin kasar", requestedItems: "Item diminta", platformItemsBody: "Produk, kuantiti, harga yang dibenarkan dan status penghantaran", companyItemsBody: "Item katalog dan anggaran harga pelanggan yang dihantar untuk kelulusan", line: "Baris", item: "Item", product: "Produk", quantity: "Kuantiti", buyTotal: "Jumlah belian", customerTotal: "Jumlah pelanggan", unitPrice: "Harga unit", lineTotal: "Anggaran jumlah baris", delivery: "Penghantaran", notAssigned: "Belum ditugaskan", operationsInfo: "Maklumat operasi", requestInfo: "Maklumat permintaan dan bajet", operationsBody: "Konteks pelanggan, kewangan dan penghantaran", requestBody: "Peminta, lokasi keperluan dan kesan kelulusan", noInvoice: "Belum ada invois pelanggan", deliveryFees: "fi penghantaran", deliveryFeesBody: "Dilaporkan berasingan daripada jualan produk dan margin dalaman.", remaining: "berbaki", noBudget: "Bajet bulanan belum dikonfigurasi", committedBudget: (committed, monthly) => `${committed} diperuntukkan daripada bajet bulanan ${monthly}.`, budgetHelp: "Pentadbir syarikat boleh menetapkan bajet cawangan daripada halaman Cawangan.", fulfilment: "Pemenuhan Axora", fulfilmentBody: "Axora hanya boleh memulakan persediaan pesanan selepas syarikat pelanggan meluluskan permintaan ini.", rejected: "Syarikat menolak permintaan ini.", waitingApproval: "Menunggu kelulusan syarikat.", approvalRequired: "Pelulus syarikat yang dibenarkan mesti membuat keputusan sebelum persediaan pesanan bermula.", nextStatus: "Status seterusnya dibenarkan", updateStatus: "Kemas kini status pemenuhan", readOnly: "Akses baca sahaja", closed: "Aliran kerja ini ditutup.", readOnlyBody: "Peranan anda boleh melihat tetapi tidak boleh mengubah status permintaan.", closedBody: "Permintaan selesai dan dibatalkan adalah baca sahaja.", companyApproval: "Kelulusan syarikat", companyApprovalBody: "Pelulus syarikat menentukan sama ada permintaan boleh menggunakan bajet cawangan.", waitingDecision: "Menunggu keputusan syarikat.", approvedBy: (name) => `Diluluskan${name ? ` oleh ${name}` : ""}.`, companyRejected: "Ditolak oleh syarikat.", afterApproval: "Axora memulakan pemenuhan hanya selepas kelulusan.", decisionRecorded: "Keputusan direkodkan dalam sejarah permintaan.", reviewApproval: "Semak kelulusan", timeline: "Garis masa", workflowUpdated: "Aliran kerja dikemas kini", byActor: (name) => ` oleh ${name}`, bySystem: " oleh sistem Axora", requestCreated: "Permintaan dicipta", approvalTimeline: (status) => `Kelulusan syarikat: ${status}`, awaitingApprover: "Menunggu pelulus yang dibenarkan", currentPosition: "Kedudukan pemenuhan Axora semasa",
  workflow: { "request.submitted": "Permintaan dihantar", "request.approved": "Syarikat meluluskan permintaan", "request.rejected": "Syarikat menolak permintaan", "quotation.requested": "Pemprosesan terdahulu bermula", "quotation.received": "Sebut harga terdahulu direkod", "supplier.selected": "Pilihan terdahulu direkod", "order.confirmed": "Pesanan disahkan", "preparation.started": "Persediaan bermula", "preparation.updated": "Persediaan pesanan dikemas kini", "delivery.updated": "Kemas kini penghantaran direkod", "delivery.scheduled": "Penghantaran dijadualkan", "driver.assignment_rejected": "Pemandu menolak tugasan", "delivery.accepted": "Pemandu menerima penghantaran", "delivery.arrived": "Pemandu tiba", "delivery.attempted": "Penghantaran dicuba", "delivery.partially_delivered": "Pemandu melaporkan penghantaran separa", "delivery.issue_reported": "Pemandu melaporkan isu penghantaran", "delivery.note_added": "Catatan pemandu ditambah", "delivery.out_for_delivery": "Dalam penghantaran", "delivery.evidence_recorded": "Bukti pemandu direkodkan", "delivery.partial_evidence_recorded": "Bukti penghantaran separa direkodkan", "delivery.delayed": "Penghantaran lewat", "delivery.failed": "Penghantaran gagal", "delivery.completed": "Penghantaran selesai", "receipt.confirmed": "Penerimaan disahkan", "discrepancy.opened": "Percanggahan penerimaan dibuka", "invoice.issued": "Invois dikeluarkan", "payment.status_changed": "Status bayaran dikemas kini", "request.completed": "Permintaan selesai", "request.cancelled": "Permintaan dibatalkan", "request.on_hold": "Permintaan ditangguhkan" },
  readyToPay: "Sedia untuk dibayar", payBody: (amount) => `Jumlah akhir yang dikira oleh pelayan ialah ${amount}.`, pay: "Bayar", paid: "Dibayar",
  downloadInvoice: "Muat turun PDF invois", invoicePreparing: "PDF invois muktamad sedang disediakan.", invoiceEmailStatus: (status) => `E-mel invois: ${status.toLowerCase().replaceAll("_", " ")}`,
  cancellationTitle: "Batalkan permintaan pembelian", cancellationBody: "Pembatalan sebelum bayaran melepaskan baki rizab bajet. Permintaan berbayar tidak boleh dibatalkan di sini.", cancelRequest: "Batalkan permintaan", cancellationComplete: "Permintaan dibatalkan dan baki rizab bajet dilepaskan.", cancellationFailed: "Permintaan tidak dapat dibatalkan dalam keadaan semasa.",
};

export const REQUEST_DETAIL_MESSAGES: Record<SupportedLocale, RequestDetailMessages> = { en, ar, ms };
export function requestDetailMessages(locale: SupportedLocale = "en") { return REQUEST_DETAIL_MESSAGES[locale]; }
