import type { SupportedLocale } from "./i18n";

interface ShopMessages {
  aria: string; heading: string; intro: string; searchInside: (name: string) => string; searchPlaceholder: string; searchAria: string; clearSearch: string;
  cartAria: string; cartItems: (count: number) => string; emptyCart: string; cartSummary: (quantity: number, subtotal: string) => string; emptyCartBody: string; review: string;
  breadcrumb: string; shop: string; browse: string; byCategory: string; chooseDepartment: string; department: string; departments: string; product: string; products: string; browseDepartment: string;
  allDepartments: string; departmentLabel: string; chooseOrView: string; viewAll: (count: number) => string; chooseSubcategory: string;
  back: string; found: (count: number) => string; loadingProducts: string; sortBy: string; recommended: string; nameAsc: string; priceAsc: string; priceDesc: string; fastest: string; lowestMoq: string;
  per: string; sameDay: string; days: (count: number) => string; added: string; add: string; viewOnly: string; noMatch: string; noMatchBody: string;
  showing: (shown: number, total: number) => string; loading: string; loadMore: string; loadError: string; loadMoreError: string; searchResults: string; searchIn: (name: string) => string; allIn: (name: string) => string;
  addedNotice: (name: string) => string; duplicateNotice: (name: string) => string;
}

const en: ShopMessages = {
  searchIn: (name) => `Search in ${name}`,
  allIn: (name) => `All ${name}`,
  aria: "Axora shop", heading: "What does your branch need today?", intro: "Search directly or browse departments and subcategories visually.", searchInside: (name) => `Search inside ${name}`, searchPlaceholder: "Search products, codes, brands, or categories", searchAria: "Search the Axora shop", clearSearch: "Clear shop search", cartAria: "Purchase request cart", cartItems: (count) => `${count} ${count === 1 ? "item" : "items"} in your request cart`, emptyCart: "Your request cart is empty", cartSummary: (quantity, subtotal) => `${quantity} units · ${subtotal} subtotal`, emptyCartBody: "Add products, then review quantities before submitting.", review: "Review request", breadcrumb: "Shop breadcrumb", shop: "Shop", browse: "Browse departments", byCategory: "Shop by category", chooseDepartment: "Choose a department to view its subcategories.", department: "department", departments: "departments", product: "product", products: "products", browseDepartment: "Browse department", allDepartments: "All departments", departmentLabel: "Department", chooseOrView: "Choose a subcategory or view every product in this department.", viewAll: (count) => `View all ${count} products`, chooseSubcategory: "Choose a subcategory", back: "Back", found: (count) => `${count.toLocaleString()} products found`, loadingProducts: "Loading products", sortBy: "Sort by", recommended: "Recommended", nameAsc: "Name: A–Z", priceAsc: "Price: low to high", priceDesc: "Price: high to low", fastest: "Fastest delivery", lowestMoq: "Lowest MOQ", per: "per", sameDay: "Same day", days: (count) => `${count} day${count === 1 ? "" : "s"}`, added: "Added to cart", add: "Add to cart", viewOnly: "View only", noMatch: "No matching products", noMatchBody: "Try another search or return to the subcategories.", showing: (shown, total) => `Showing ${shown.toLocaleString()} of ${total.toLocaleString()}`, loading: "Loading…", loadMore: "Load more products", loadError: "Unable to load shop products.", loadMoreError: "Unable to load more products.", searchResults: "Search results", addedNotice: (name) => `${name} added to the request cart.`, duplicateNotice: (name) => `${name} is already in the request cart.`,
};

const ar: ShopMessages = {
  searchIn: (name) => `البحث في ${name}`,
  allIn: (name) => `كل ${name}`,
  aria: "متجر أكسورا", heading: "ماذا يحتاج فرعك اليوم؟", intro: "ابحث مباشرة أو تصفح الأقسام والفئات الفرعية بصرياً.", searchInside: (name) => `ابحث داخل ${name}`, searchPlaceholder: "ابحث عن منتج أو رمز أو علامة أو فئة", searchAria: "البحث في متجر أكسورا", clearSearch: "مسح بحث المتجر", cartAria: "سلة طلب الشراء", cartItems: (count) => `${count} بنود في سلة طلبك`, emptyCart: "سلة طلبك فارغة", cartSummary: (quantity, subtotal) => `${quantity} وحدات · ${subtotal} مجموع فرعي`, emptyCartBody: "أضف المنتجات ثم راجع الكميات قبل الإرسال.", review: "مراجعة الطلب", breadcrumb: "مسار المتجر", shop: "المتجر", browse: "تصفح الأقسام", byCategory: "تسوق حسب الفئة", chooseDepartment: "اختر قسماً لعرض فئاته الفرعية.", department: "قسم", departments: "أقسام", product: "منتج", products: "منتجات", browseDepartment: "تصفح القسم", allDepartments: "كل الأقسام", departmentLabel: "القسم", chooseOrView: "اختر فئة فرعية أو اعرض كل منتجات هذا القسم.", viewAll: (count) => `عرض كل المنتجات (${count})`, chooseSubcategory: "اختر فئة فرعية", back: "رجوع", found: (count) => `تم العثور على ${count.toLocaleString("ar-MY")} منتجات`, loadingProducts: "جارٍ تحميل المنتجات", sortBy: "الترتيب حسب", recommended: "موصى به", nameAsc: "الاسم: أ–ي", priceAsc: "السعر: الأقل أولاً", priceDesc: "السعر: الأعلى أولاً", fastest: "الأسرع تسليماً", lowestMoq: "أقل حد للطلب", per: "لكل", sameDay: "اليوم نفسه", days: (count) => `${count} أيام`, added: "أضيف إلى السلة", add: "إضافة إلى السلة", viewOnly: "عرض فقط", noMatch: "لا توجد منتجات مطابقة", noMatchBody: "جرّب بحثاً آخر أو ارجع إلى الفئات الفرعية.", showing: (shown, total) => `عرض ${shown.toLocaleString("ar-MY")} من ${total.toLocaleString("ar-MY")}`, loading: "جارٍ التحميل…", loadMore: "تحميل مزيد من المنتجات", loadError: "تعذر تحميل منتجات المتجر.", loadMoreError: "تعذر تحميل مزيد من المنتجات.", searchResults: "نتائج البحث", addedNotice: (name) => `تمت إضافة ${name} إلى سلة الطلب.`, duplicateNotice: (name) => `${name} موجود بالفعل في سلة الطلب.`,
};

const ms: ShopMessages = {
  searchIn: (name) => `Cari dalam ${name}`,
  allIn: (name) => `Semua ${name}`,
  aria: "Kedai Axora", heading: "Apakah yang diperlukan oleh cawangan anda hari ini?", intro: "Cari terus atau semak jabatan dan subkategori secara visual.", searchInside: (name) => `Cari dalam ${name}`, searchPlaceholder: "Cari produk, kod, jenama atau kategori", searchAria: "Cari Kedai Axora", clearSearch: "Kosongkan carian kedai", cartAria: "Troli permintaan pembelian", cartItems: (count) => `${count} item dalam troli permintaan anda`, emptyCart: "Troli permintaan anda kosong", cartSummary: (quantity, subtotal) => `${quantity} unit · subjumlah ${subtotal}`, emptyCartBody: "Tambah produk, kemudian semak kuantiti sebelum menghantar.", review: "Semak permintaan", breadcrumb: "Jejak Kedai", shop: "Kedai", browse: "Semak jabatan", byCategory: "Beli mengikut kategori", chooseDepartment: "Pilih jabatan untuk melihat subkategorinya.", department: "jabatan", departments: "jabatan", product: "produk", products: "produk", browseDepartment: "Semak jabatan", allDepartments: "Semua jabatan", departmentLabel: "Jabatan", chooseOrView: "Pilih subkategori atau lihat semua produk dalam jabatan ini.", viewAll: (count) => `Lihat semua ${count} produk`, chooseSubcategory: "Pilih subkategori", back: "Kembali", found: (count) => `${count.toLocaleString("ms-MY")} produk ditemui`, loadingProducts: "Memuatkan produk", sortBy: "Susun mengikut", recommended: "Disyorkan", nameAsc: "Nama: A–Z", priceAsc: "Harga: rendah ke tinggi", priceDesc: "Harga: tinggi ke rendah", fastest: "Penghantaran terpantas", lowestMoq: "MOQ terendah", per: "setiap", sameDay: "Hari yang sama", days: (count) => `${count} hari`, added: "Ditambah ke troli", add: "Tambah ke troli", viewOnly: "Lihat sahaja", noMatch: "Tiada produk sepadan", noMatchBody: "Cuba carian lain atau kembali ke subkategori.", showing: (shown, total) => `Menunjukkan ${shown.toLocaleString("ms-MY")} daripada ${total.toLocaleString("ms-MY")}`, loading: "Memuatkan…", loadMore: "Muatkan lebih banyak produk", loadError: "Produk kedai tidak dapat dimuatkan.", loadMoreError: "Lebih banyak produk tidak dapat dimuatkan.", searchResults: "Hasil carian", addedNotice: (name) => `${name} ditambah ke troli permintaan.`, duplicateNotice: (name) => `${name} sudah ada dalam troli permintaan.`,
};

export const SHOP_MESSAGES: Record<SupportedLocale, ShopMessages> = { en, ar, ms };
export function shopMessages(locale: SupportedLocale = "en") { return SHOP_MESSAGES[locale]; }
