import type { SupportedLocale } from "./i18n";
import type { UserRole } from "./types";

interface UserFormMessages {
  fullName: string; workEmail: string; jobTitle: string; optional: string; invitationLanguage: string; languageHelp: string;
  role: string; selectRole: string; customerCompany: string; selectCompany: string; assignedBranch: string; selectBranch: string; companyWide: string;
  branchLimited: string; branchOptional: string; department: string; selectDepartment: string; assignmentLevel: string;
  branchScope: string; departmentScope: string; roleOverview: string; accessIncluded: string; organizationScope: string;
  roleChanged: string; secureSetup: string; secureSetupBody: string; creating: string; sending: string; create: string;
  categories: Record<string, string>; accessGroups: Record<string, string>;
  roles: Partial<Record<UserRole, { label: string; description: string }>>;
}

const en: UserFormMessages = {
  fullName: "Full name", workEmail: "Work email", jobTitle: "Job title", optional: "optional", invitationLanguage: "Invitation language", languageHelp: "The setup email and first account experience use this language.", role: "Role", selectRole: "Select a role", customerCompany: "Customer company", selectCompany: "Select company", assignedBranch: "Assigned branch", selectBranch: "Select branch", companyWide: "Company-wide", branchLimited: "This role is securely limited to one branch.", branchOptional: "Choose a branch or keep company-wide access.", department: "Department", selectDepartment: "Select department", assignmentLevel: "Assignment level", branchScope: "Branch", departmentScope: "Department", roleOverview: "Role overview", accessIncluded: "Access included with this role", organizationScope: "Organization scope", roleChanged: "Role changed. Access and organization settings were updated for the selected role.", secureSetup: "Secure account setup", secureSetupBody: "Axora emails a single-use setup link. The recipient creates their own password; administrators never see or share it.", creating: "Creating account and sending setup email…", sending: "Sending invitation…", create: "Create account & send invite", categories: { Axora: "Axora Platform", Company: "Customer Company", Delivery: "Delivery Operations" }, accessGroups: { Platform: "Platform", Companies: "Companies", "User Management": "User Management", Organization: "Organization", Catalogue: "Catalogue", Requests: "Requests", Approvals: "Approvals", Budgets: "Budgets", Finance: "Finance", Delivery: "Delivery", Receiving: "Receiving", Documents: "Documents", Reports: "Reports", "Other access": "Other access" }, roles: {
    PLATFORM_OWNER: { label: "Axora platform owner", description: "Full platform governance and protected tenant administration." }, HUMAN_RESOURCES_MANAGEMENT: { label: "Human Resources Management", description: "Assigns company leads to eligible account managers and monitors onboarding." }, CLIENT_ACCOUNT_MANAGER: { label: "Client Account Manager", description: "Axora employee responsible for assigned leads and customer companies; company assignments are added separately." }, DELIVERY_GUY: { label: "Delivery Guy", description: "Buys requested items and completes only assigned deliveries with receipt evidence." }, PLATFORM_OPERATIONS: { label: "Axora operations administrator", description: "Catalog and paid-delivery coordination without owner governance." }, TECHNICAL_SUPPORT: { label: "Technical support", description: "Audited diagnostics and safe support actions without commercial authority." }, COMPANY_ADMIN: { label: "Company administrator", description: "People, branches, budgets, and company-wide procurement oversight." }, BRANCH_ADMIN: { label: "Branch administrator", description: "People and procurement activity for one assigned branch." }, DEPARTMENT_ADMIN: { label: "Department administrator", description: "People, requests, approvals, and budget visibility for one assigned department." }, COMPANY_APPROVER: { label: "Company approver", description: "Eligible approval decisions across one customer company." }, BRANCH_APPROVER: { label: "Branch approver", description: "Eligible approval decisions for one assigned branch." }, REQUESTER: { label: "Purchase requester", description: "Browses products and creates purchase requests for one assigned branch or department." }, FINANCE_REVIEWER: { label: "Finance reviewer", description: "Customer invoices, payment status and finance records." }, AUDITOR: { label: "Read-only auditor", description: "Read-only evidence and audit history within the assigned scope." }, RECEIVING_USER: { label: "Receiving user", description: "Independent delivery inspection and receipt confirmation." }, DELIVERY_DRIVER: { label: "Delivery driver", description: "Assigned mobile delivery jobs and evidence only." },
  },
};

const ar: UserFormMessages = {
  ...en, fullName: "الاسم الكامل", workEmail: "بريد العمل", jobTitle: "المسمى الوظيفي", optional: "اختياري", invitationLanguage: "لغة الدعوة", languageHelp: "تستخدم رسالة الإعداد وتجربة الحساب الأولى هذه اللغة.", role: "الدور", selectRole: "اختر دوراً", customerCompany: "شركة العميل", selectCompany: "اختر الشركة", assignedBranch: "الفرع المعين", selectBranch: "اختر الفرع", companyWide: "الشركة بالكامل", branchLimited: "هذا الدور مقيد بأمان بفرع واحد.", branchOptional: "اختر فرعاً أو احتفظ بصلاحية الشركة بالكامل.", department: "القسم", selectDepartment: "اختر القسم", assignmentLevel: "مستوى التعيين", branchScope: "فرع", departmentScope: "قسم", roleOverview: "نظرة عامة على الدور", accessIncluded: "الصلاحيات المشمولة مع هذا الدور", organizationScope: "نطاق المؤسسة", roleChanged: "تم تغيير الدور. تم تحديث الصلاحيات وإعدادات المؤسسة للدور المحدد.", secureSetup: "إعداد حساب آمن", secureSetupBody: "ترسل أكسورا رابط إعداد لمرة واحدة. ينشئ المستلم كلمة مروره بنفسه، ولا يراها المديرون أو يشاركونها.", creating: "جارٍ إنشاء الحساب وإرسال رسالة الإعداد…", sending: "جارٍ إرسال الدعوة…", create: "إنشاء الحساب وإرسال الدعوة", categories: { Axora: "منصة أكسورا", Company: "شركة العميل", Delivery: "عمليات التسليم" }, accessGroups: { Platform: "المنصة", Companies: "الشركات", "User Management": "إدارة المستخدمين", Organization: "المؤسسة", Catalogue: "الكتالوج", Requests: "الطلبات", Approvals: "الموافقات", Budgets: "الميزانيات", Finance: "المالية", Delivery: "التسليم", Receiving: "الاستلام", Documents: "المستندات", Reports: "التقارير", "Other access": "صلاحيات أخرى" }, roles: {
    PLATFORM_OWNER: { label: "مالك منصة أكسورا", description: "حوكمة كاملة للمنصة وإدارة محمية للشركات المستأجرة." }, HUMAN_RESOURCES_MANAGEMENT: { label: "إدارة الموارد البشرية", description: "تسند العملاء المحتملين إلى مديري الحسابات المؤهلين وتتابع التهيئة." }, CLIENT_ACCOUNT_MANAGER: { label: "مدير حساب العميل", description: "موظف أكسورا مسؤول عن العملاء المحتملين والشركات المسندة؛ يتم إسناد الشركات بشكل منفصل." }, DELIVERY_GUY: { label: "مسؤول التوصيل", description: "يشتري البنود وينجز عمليات التسليم المسندة فقط مع أدلة الاستلام." }, PLATFORM_OPERATIONS: { label: "مدير عمليات أكسورا", description: "إدارة الكتالوج والطلبات المدفوعة والتسليم دون صلاحيات حوكمة المالك." }, TECHNICAL_SUPPORT: { label: "الدعم التقني", description: "تشخيصات مدققة وإجراءات دعم آمنة دون صلاحية تجارية." }, COMPANY_ADMIN: { label: "مدير الشركة", description: "إدارة الأشخاص والفروع والميزانيات والمشتريات على مستوى الشركة." }, BRANCH_ADMIN: { label: "مدير الفرع", description: "إدارة الأشخاص ونشاط المشتريات لفرع معين واحد." }, DEPARTMENT_ADMIN: { label: "مدير القسم", description: "إدارة الأشخاص والطلبات والموافقات ورؤية الميزانية لقسم معين." }, COMPANY_APPROVER: { label: "معتمد الشركة", description: "قرارات اعتماد مؤهلة عبر شركة عميل واحدة." }, BRANCH_APPROVER: { label: "معتمد الفرع", description: "قرارات اعتماد مؤهلة لفرع معين واحد." }, REQUESTER: { label: "مقدم طلب شراء", description: "يتصفح المنتجات وينشئ طلبات شراء ضمن فرع أو قسم معين." }, FINANCE_REVIEWER: { label: "مراجع مالي", description: "فواتير العملاء وحالة الدفع والسجلات المالية." }, AUDITOR: { label: "مدقق للقراءة فقط", description: "أدلة وسجل تدقيق للقراءة فقط ضمن النطاق المعين." }, RECEIVING_USER: { label: "مستخدم الاستلام", description: "فحص مستقل للتسليم وتأكيد الاستلام." }, DELIVERY_DRIVER: { label: "سائق التسليم", description: "مهام التسليم المتنقلة والأدلة المسندة فقط." },
  },
};

const ms: UserFormMessages = {
  ...en, fullName: "Nama penuh", workEmail: "E-mel kerja", jobTitle: "Jawatan", optional: "pilihan", invitationLanguage: "Bahasa jemputan", languageHelp: "E-mel persediaan dan pengalaman akaun pertama menggunakan bahasa ini.", role: "Peranan", selectRole: "Pilih peranan", customerCompany: "Syarikat pelanggan", selectCompany: "Pilih syarikat", assignedBranch: "Cawangan ditugaskan", selectBranch: "Pilih cawangan", companyWide: "Seluruh syarikat", branchLimited: "Peranan ini dihadkan dengan selamat kepada satu cawangan.", branchOptional: "Pilih cawangan atau kekalkan akses seluruh syarikat.", department: "Jabatan", selectDepartment: "Pilih jabatan", assignmentLevel: "Tahap tugasan", branchScope: "Cawangan", departmentScope: "Jabatan", roleOverview: "Ringkasan peranan", accessIncluded: "Akses yang termasuk dengan peranan ini", organizationScope: "Skop organisasi", roleChanged: "Peranan diubah. Akses dan tetapan organisasi telah dikemas kini untuk peranan yang dipilih.", secureSetup: "Persediaan akaun selamat", secureSetupBody: "Axora menghantar pautan persediaan sekali guna. Penerima mencipta kata laluan sendiri; pentadbir tidak pernah melihat atau berkongsinya.", creating: "Mencipta akaun dan menghantar e-mel persediaan…", sending: "Menghantar jemputan…", create: "Cipta akaun & hantar jemputan", categories: { Axora: "Platform Axora", Company: "Syarikat Pelanggan", Delivery: "Operasi Penghantaran" }, accessGroups: { Platform: "Platform", Companies: "Syarikat", "User Management": "Pengurusan Pengguna", Organization: "Organisasi", Catalogue: "Katalog", Requests: "Permintaan", Approvals: "Kelulusan", Budgets: "Bajet", Finance: "Kewangan", Delivery: "Penghantaran", Receiving: "Penerimaan", Documents: "Dokumen", Reports: "Laporan", "Other access": "Akses lain" }, roles: {
    PLATFORM_OWNER: { label: "Pemilik platform Axora", description: "Tadbir urus platform penuh dan pentadbiran penyewa terlindung." }, HUMAN_RESOURCES_MANAGEMENT: { label: "Pengurusan Sumber Manusia", description: "Menugaskan lead kepada pengurus akaun yang layak dan memantau pendaftaran." }, CLIENT_ACCOUNT_MANAGER: { label: "Pengurus Akaun Pelanggan", description: "Pekerja Axora untuk lead dan syarikat yang ditugaskan; tugasan syarikat dibuat secara berasingan." }, DELIVERY_GUY: { label: "Penghantar", description: "Membeli item dan menyelesaikan penghantaran yang ditugaskan sahaja dengan bukti resit." }, PLATFORM_OPERATIONS: { label: "Pentadbir operasi Axora", description: "Penyelarasan katalog, permintaan berbayar dan penghantaran tanpa kuasa pemilik." }, TECHNICAL_SUPPORT: { label: "Sokongan teknikal", description: "Diagnostik diaudit dan tindakan sokongan selamat tanpa kuasa komersial." }, COMPANY_ADMIN: { label: "Pentadbir syarikat", description: "Pengawasan orang, cawangan, bajet dan perolehan seluruh syarikat." }, BRANCH_ADMIN: { label: "Pentadbir cawangan", description: "Aktiviti orang dan perolehan untuk satu cawangan ditugaskan." }, DEPARTMENT_ADMIN: { label: "Pentadbir jabatan", description: "Orang, permintaan, kelulusan dan keterlihatan bajet untuk satu jabatan." }, COMPANY_APPROVER: { label: "Pelulus syarikat", description: "Keputusan kelulusan yang layak merentas satu syarikat pelanggan." }, BRANCH_APPROVER: { label: "Pelulus cawangan", description: "Keputusan kelulusan yang layak untuk satu cawangan ditugaskan." }, REQUESTER: { label: "Peminta pembelian", description: "Melayari produk dan mencipta permintaan pembelian untuk cawangan atau jabatan ditugaskan." }, FINANCE_REVIEWER: { label: "Penyemak kewangan", description: "Invois pelanggan, status bayaran dan rekod kewangan." }, AUDITOR: { label: "Juruaudit baca sahaja", description: "Bukti dan sejarah audit baca sahaja dalam skop ditugaskan." }, RECEIVING_USER: { label: "Pengguna penerimaan", description: "Pemeriksaan penghantaran dan pengesahan penerimaan bebas." }, DELIVERY_DRIVER: { label: "Pemandu penghantaran", description: "Kerja penghantaran mudah alih dan bukti ditugaskan sahaja." },
  },
};

export const USER_FORM_MESSAGES: Record<SupportedLocale, UserFormMessages> = { en, ar, ms };
export function userFormMessages(locale: SupportedLocale = "en") { return USER_FORM_MESSAGES[locale]; }
export function localizedAccountRole(role: UserRole, locale: SupportedLocale = "en") { return USER_FORM_MESSAGES[locale].roles[role]; }
