import { PageHeader } from "@/components/PageHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { requirePagePermission } from "@/lib/auth";
import { listCompanies } from "@/lib/repository";
import { COD_PAYMENT_METHOD } from "@/lib/types";
import { operationalMessage, operationalNumber, operationalStatus, type OperationalMessageKey } from "@/lib/operational-i18n";
import { createCompanyAction, regenerateCompanyBrandAction, setMasterActiveAction } from "../masters/actions";

export default async function CompaniesPage() {
  const actor = await requirePagePermission("manage_companies");
  const locale = actor.preferredLocale ?? "en";
  const m = (key: OperationalMessageKey, values?: Record<string, string | number>) => operationalMessage(locale, key, values);
  const companies = await listCompanies(actor);
  return <><PageHeader eyebrow={m("companies.eyebrow")} title={m("companies.title")} description={m("companies.description")} />
    <section className="split-layout"><article className="panel"><div className="panel-header"><div><h2>{m("companies.register")}</h2><p>{m("companies.count", { count: operationalNumber(locale, companies.length) })}</p></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>{m("companies.code")}</th><th>{m("companies.company")}</th><th>{m("companies.industry")}</th><th>{m("companies.contact")}</th><th>{m("companies.terms")}</th><th>{m("common.status")}</th><th>{m("common.action")}</th></tr></thead><tbody>{companies.map((company) => <tr key={company.id}><td><strong>{company.code}</strong></td><td><strong>{company.name}</strong><br /><span className="subtle">{company.billingCycle}</span></td><td>{company.industry}</td><td>{company.mainContactName}<br /><span className="subtle">{company.mainContactEmail}</span></td><td>{company.paymentTerms}</td><td><StatusBadge>{operationalStatus(locale, company.status)}</StatusBadge></td><td><div className="table-action-stack"><form action={setMasterActiveAction.bind(null, "companies", company.id, company.status !== "Active")}><button className="button button-secondary" type="submit">{m(company.status === "Active" ? "common.deactivate" : "common.activate")}</button></form><details><summary>{m("companies.replaceLogo")}</summary><form action={regenerateCompanyBrandAction.bind(null, company.id)}><label><span className="sr-only">{m("companies.newLogo", { name: company.name })}</span><input name="logo" type="file" accept="image/png,image/jpeg,image/webp" required /></label><button className="button button-secondary" type="submit">{m("companies.regenerate")}</button></form></details></div></td></tr>)}</tbody></table></div></article>
    <form action={createCompanyAction} className="panel form-panel"><h2>{m("companies.createTitle")}</h2><p>{m("companies.createIntro")}</p><div className="form-grid">
      <label className="field-full">{m("companies.name")}<input name="name" required /></label><label>{m("companies.industry")}<input name="industry" required /></label><label>{m("companies.billingCycle")}<select name="billingCycle"><option value="Monthly">{m("companies.monthly")}</option><option value="Per order">{m("companies.perOrder")}</option><option value="Weekly">{m("companies.weekly")}</option></select></label>
      <label className="field-full">{m("companies.info")}<textarea name="companyInformation" required maxLength={3000} /></label><label className="field-full">{m("companies.website")}<input name="websiteUrl" type="url" inputMode="url" placeholder="https://example.com" /></label>
      <label className="field-full">{m("companies.logo")}<input name="logo" type="file" accept="image/png,image/jpeg,image/webp" required /><small>{m("companies.logoHelp")}</small></label>
      <label>{m("companies.mainName")}<input name="mainContactName" required /></label><label>{m("companies.mainEmail")}<input name="mainContactEmail" type="email" required /></label><label>{m("companies.mainPhone")}<input name="mainContactPhone" required /></label><label>{m("companies.terms")}<input name="paymentTerms" value={COD_PAYMENT_METHOD} readOnly required /></label>
      <label>{m("companies.billingName")}<input name="billingContactName" /></label><label>{m("companies.billingEmail")}<input name="billingContactEmail" type="email" /></label><label>{m("companies.billingPhone")}<input name="billingContactPhone" /></label><label className="field-full">{m("companies.billingAddress")}<textarea name="billingAddress" required /></label><label className="field-full">{m("companies.notes")}<textarea name="notes" /></label>
    </div><div className="form-actions"><button className="button button-primary" type="submit">{m("companies.submit")}</button></div></form></section></>;
}
