BEGIN;

-- P2-01 keeps generated branding as an unpublished draft until a human
-- reviewer accepts it. Existing active themes are preserved and backfilled as
-- published evidence; no production logo or theme is regenerated by migration.

ALTER TABLE public.company_brand_themes
  ADD COLUMN IF NOT EXISTS primary_hover text NOT NULL DEFAULT '#0B2D52',
  ADD COLUMN IF NOT EXISTS primary_active text NOT NULL DEFAULT '#0B2D52',
  ADD COLUMN IF NOT EXISTS dark_page_background text NOT NULL DEFAULT '#0A1624',
  ADD COLUMN IF NOT EXISTS dark_surface_color text NOT NULL DEFAULT '#12243A',
  ADD COLUMN IF NOT EXISTS dark_border_color text NOT NULL DEFAULT '#31445A',
  ADD COLUMN IF NOT EXISTS text_color text NOT NULL DEFAULT '#172033',
  ADD COLUMN IF NOT EXISTS inverse_text_color text NOT NULL DEFAULT '#F4F7FB',
  ADD COLUMN IF NOT EXISTS icon_color text NOT NULL DEFAULT '#344054',
  ADD COLUMN IF NOT EXISTS inverse_icon_color text NOT NULL DEFAULT '#D7DEE8',
  ADD COLUMN IF NOT EXISTS logo_variant text NOT NULL DEFAULT 'ORIGINAL',
  ADD COLUMN IF NOT EXISTS logo_placement text NOT NULL DEFAULT 'HEADER_START',
  ADD COLUMN IF NOT EXISTS theme_preference text NOT NULL DEFAULT 'LIGHT',
  ADD COLUMN IF NOT EXISTS page_configuration jsonb NOT NULL DEFAULT
    '{"schemaVersion":1,"components":["hero","requestSummary","budgetSummary","recentActivity"]}'::jsonb,
  ADD COLUMN IF NOT EXISTS manual_overrides jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS source_theme_id uuid,
  ADD COLUMN IF NOT EXISTS rollback_of_theme_id uuid;

UPDATE public.company_brand_themes
SET primary_hover=primary_color,
    primary_active=primary_color
WHERE primary_hover='#0B2D52'
  AND primary_active='#0B2D52'
  AND primary_color<>'#0B2D52';

DO $brand_theme_foreign_keys$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname='company_brand_themes_source_theme_fk'
      AND conrelid='public.company_brand_themes'::regclass
  ) THEN
    ALTER TABLE public.company_brand_themes
      ADD CONSTRAINT company_brand_themes_source_theme_fk
      FOREIGN KEY (source_theme_id)
      REFERENCES public.company_brand_themes(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname='company_brand_themes_rollback_theme_fk'
      AND conrelid='public.company_brand_themes'::regclass
  ) THEN
    ALTER TABLE public.company_brand_themes
      ADD CONSTRAINT company_brand_themes_rollback_theme_fk
      FOREIGN KEY (rollback_of_theme_id)
      REFERENCES public.company_brand_themes(id) ON DELETE RESTRICT;
  END IF;
END
$brand_theme_foreign_keys$;

CREATE OR REPLACE FUNCTION public.axora_brand_page_configuration_valid(
  p_configuration jsonb
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT jsonb_typeof(p_configuration)='object'
    AND p_configuration->>'schemaVersion'='1'
    AND jsonb_typeof(p_configuration->'components')='array'
    AND jsonb_array_length(p_configuration->'components') BETWEEN 1 AND 8
    AND NOT EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(p_configuration->'components') component
      WHERE component NOT IN (
        'hero','requestSummary','budgetSummary','recentActivity'
      )
    )
$$;

CREATE OR REPLACE FUNCTION public.axora_brand_tokens_valid(p_tokens jsonb)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT jsonb_typeof(p_tokens)='object'
    AND p_tokens ?& ARRAY[
      'primary','primaryHover','primaryActive','secondary','accent',
      'primaryForeground','secondaryForeground','pageBackground',
      'darkPageBackground','surface','darkSurface','mutedSurface',
      'border','darkBorder','text','textInverse','icon','iconInverse',
      'success','warning','danger','focusRing','link','chart'
    ]
    AND (p_tokens->>'primary') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'primaryHover') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'primaryActive') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'secondary') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'accent') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'primaryForeground') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'secondaryForeground') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'pageBackground') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'darkPageBackground') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'surface') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'darkSurface') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'mutedSurface') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'border') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'darkBorder') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'text') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'textInverse') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'icon') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'iconInverse') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'success') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'warning') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'danger') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'focusRing') ~ '^#[0-9A-F]{6}$'
    AND (p_tokens->>'link') ~ '^#[0-9A-F]{6}$'
    AND jsonb_typeof(p_tokens->'chart')='array'
    AND jsonb_array_length(p_tokens->'chart') BETWEEN 3 AND 8
    AND NOT EXISTS (
      SELECT 1 FROM jsonb_array_elements_text(p_tokens->'chart') color
      WHERE color !~ '^#[0-9A-F]{6}$'
    )
$$;

CREATE OR REPLACE FUNCTION public.axora_brand_contrast_summary_valid(
  p_summary jsonb
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT jsonb_typeof(p_summary)='object'
    AND p_summary ?& ARRAY[
      'primaryForeground','primaryHoverForeground',
      'primaryActiveForeground','secondaryForeground',
      'textOnBackground','textInverseOnDark','iconOnBackground',
      'iconInverseOnDark','linkOnBackground','focusOnBackground','passes'
    ]
    AND jsonb_typeof(p_summary->'passes')='boolean'
    AND jsonb_typeof(p_summary->'primaryForeground')='number'
    AND jsonb_typeof(p_summary->'primaryHoverForeground')='number'
    AND jsonb_typeof(p_summary->'primaryActiveForeground')='number'
    AND jsonb_typeof(p_summary->'secondaryForeground')='number'
    AND jsonb_typeof(p_summary->'textOnBackground')='number'
    AND jsonb_typeof(p_summary->'textInverseOnDark')='number'
    AND jsonb_typeof(p_summary->'iconOnBackground')='number'
    AND jsonb_typeof(p_summary->'iconInverseOnDark')='number'
    AND jsonb_typeof(p_summary->'linkOnBackground')='number'
    AND jsonb_typeof(p_summary->'focusOnBackground')='number'
$$;

ALTER TABLE public.company_brand_themes
  DROP CONSTRAINT IF EXISTS company_brand_themes_review_tokens_check;
ALTER TABLE public.company_brand_themes
  ADD CONSTRAINT company_brand_themes_review_tokens_check CHECK (
    primary_hover ~ '^#[0-9A-F]{6}$'
    AND primary_active ~ '^#[0-9A-F]{6}$'
    AND dark_page_background ~ '^#[0-9A-F]{6}$'
    AND dark_surface_color ~ '^#[0-9A-F]{6}$'
    AND dark_border_color ~ '^#[0-9A-F]{6}$'
    AND text_color ~ '^#[0-9A-F]{6}$'
    AND inverse_text_color ~ '^#[0-9A-F]{6}$'
    AND icon_color ~ '^#[0-9A-F]{6}$'
    AND inverse_icon_color ~ '^#[0-9A-F]{6}$'
    AND logo_variant IN ('ORIGINAL','MONOCHROME','INVERTED')
    AND logo_placement IN ('HEADER_START','HEADER_CENTER')
    AND theme_preference IN ('LIGHT','DARK')
    AND public.axora_brand_page_configuration_valid(page_configuration)
    AND jsonb_typeof(manual_overrides)='object'
    AND char_length(manual_overrides::text)<=16384
  );

CREATE TABLE IF NOT EXISTS public.company_brand_theme_workflows (
  theme_id uuid PRIMARY KEY
    REFERENCES public.company_brand_themes(id) ON DELETE RESTRICT,
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE RESTRICT,
  status text NOT NULL CHECK (
    status IN (
      'REVIEW_REQUIRED','APPROVED','PUBLISHED','REJECTED','SUPERSEDED'
    )
  ),
  updated_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS company_brand_one_open_review_uq
  ON public.company_brand_theme_workflows(company_id)
  WHERE status IN ('REVIEW_REQUIRED','APPROVED');
CREATE INDEX IF NOT EXISTS company_brand_workflow_status_idx
  ON public.company_brand_theme_workflows(company_id,status,updated_at DESC);

CREATE TABLE IF NOT EXISTS public.company_brand_theme_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  theme_id uuid NOT NULL
    REFERENCES public.company_brand_themes(id) ON DELETE RESTRICT,
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE RESTRICT,
  source_logo_id uuid NOT NULL
    REFERENCES public.company_logos(id) ON DELETE RESTRICT,
  event_version integer NOT NULL CHECK (event_version>0),
  from_status text,
  status text NOT NULL CHECK (
    status IN (
      'LOGO_UPLOADED','ANALYSIS_QUEUED','DRAFT_GENERATED',
      'REVIEW_REQUIRED','APPROVED','PUBLISHED','REJECTED','SUPERSEDED'
    )
  ),
  action text NOT NULL CHECK (action ~ '^[A-Z][A-Z_]{2,63}$'),
  reason text NOT NULL CHECK (char_length(btrim(reason)) BETWEEN 3 AND 1000),
  actor_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  role_assignment_id uuid REFERENCES public.role_assignments(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(theme_id,event_version)
);

CREATE INDEX IF NOT EXISTS company_brand_events_company_time_idx
  ON public.company_brand_theme_events(company_id,created_at DESC,id);

INSERT INTO public.company_brand_theme_workflows(
  theme_id,company_id,status,updated_by,updated_at
)
SELECT theme.id,theme.company_id,
  CASE WHEN theme.active THEN 'PUBLISHED' ELSE 'SUPERSEDED' END,
  theme.created_by,theme.created_at
FROM public.company_brand_themes theme
ON CONFLICT (theme_id) DO NOTHING;

INSERT INTO public.company_brand_theme_events(
  theme_id,company_id,source_logo_id,event_version,from_status,status,
  action,reason,actor_id,created_at
)
SELECT theme.id,theme.company_id,theme.source_logo_id,1,NULL,
  CASE WHEN theme.active THEN 'PUBLISHED' ELSE 'SUPERSEDED' END,
  'MIGRATION_BACKFILL',
  'Preserved existing company branding during reviewed workflow migration',
  theme.created_by,theme.created_at
FROM public.company_brand_themes theme
WHERE NOT EXISTS (
  SELECT 1 FROM public.company_brand_theme_events event
  WHERE event.theme_id=theme.id
);

CREATE OR REPLACE FUNCTION public.protect_company_brand_theme()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.id IS DISTINCT FROM OLD.id
    OR NEW.company_id IS DISTINCT FROM OLD.company_id
    OR NEW.source_logo_id IS DISTINCT FROM OLD.source_logo_id
    OR NEW.version IS DISTINCT FROM OLD.version
    OR NEW.algorithm_version IS DISTINCT FROM OLD.algorithm_version
    OR NEW.primary_color IS DISTINCT FROM OLD.primary_color
    OR NEW.primary_hover IS DISTINCT FROM OLD.primary_hover
    OR NEW.primary_active IS DISTINCT FROM OLD.primary_active
    OR NEW.secondary_color IS DISTINCT FROM OLD.secondary_color
    OR NEW.accent_color IS DISTINCT FROM OLD.accent_color
    OR NEW.primary_foreground IS DISTINCT FROM OLD.primary_foreground
    OR NEW.secondary_foreground IS DISTINCT FROM OLD.secondary_foreground
    OR NEW.page_background IS DISTINCT FROM OLD.page_background
    OR NEW.dark_page_background IS DISTINCT FROM OLD.dark_page_background
    OR NEW.surface_color IS DISTINCT FROM OLD.surface_color
    OR NEW.dark_surface_color IS DISTINCT FROM OLD.dark_surface_color
    OR NEW.muted_surface IS DISTINCT FROM OLD.muted_surface
    OR NEW.border_color IS DISTINCT FROM OLD.border_color
    OR NEW.dark_border_color IS DISTINCT FROM OLD.dark_border_color
    OR NEW.text_color IS DISTINCT FROM OLD.text_color
    OR NEW.inverse_text_color IS DISTINCT FROM OLD.inverse_text_color
    OR NEW.icon_color IS DISTINCT FROM OLD.icon_color
    OR NEW.inverse_icon_color IS DISTINCT FROM OLD.inverse_icon_color
    OR NEW.success_color IS DISTINCT FROM OLD.success_color
    OR NEW.warning_color IS DISTINCT FROM OLD.warning_color
    OR NEW.danger_color IS DISTINCT FROM OLD.danger_color
    OR NEW.focus_ring IS DISTINCT FROM OLD.focus_ring
    OR NEW.link_color IS DISTINCT FROM OLD.link_color
    OR NEW.chart_colors IS DISTINCT FROM OLD.chart_colors
    OR NEW.extraction_summary IS DISTINCT FROM OLD.extraction_summary
    OR NEW.contrast_summary IS DISTINCT FROM OLD.contrast_summary
    OR NEW.logo_variant IS DISTINCT FROM OLD.logo_variant
    OR NEW.logo_placement IS DISTINCT FROM OLD.logo_placement
    OR NEW.theme_preference IS DISTINCT FROM OLD.theme_preference
    OR NEW.page_configuration IS DISTINCT FROM OLD.page_configuration
    OR NEW.manual_overrides IS DISTINCT FROM OLD.manual_overrides
    OR NEW.source_theme_id IS DISTINCT FROM OLD.source_theme_id
    OR NEW.rollback_of_theme_id IS DISTINCT FROM OLD.rollback_of_theme_id
    OR NEW.created_by IS DISTINCT FROM OLD.created_by
    OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'Company brand theme evidence is immutable';
  END IF;
  IF NEW.active IS DISTINCT FROM OLD.active
    AND current_setting('axora.brand_publication',true)<>'on' THEN
    RAISE EXCEPTION 'Theme activation requires controlled publication';
  END IF;
  RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION public.protect_company_brand_logo()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.id IS DISTINCT FROM OLD.id
    OR NEW.company_id IS DISTINCT FROM OLD.company_id
    OR NEW.version IS DISTINCT FROM OLD.version
    OR NEW.file_name IS DISTINCT FROM OLD.file_name
    OR NEW.content_type IS DISTINCT FROM OLD.content_type
    OR NEW.logo_content IS DISTINCT FROM OLD.logo_content
    OR NEW.sha256 IS DISTINCT FROM OLD.sha256
    OR NEW.width IS DISTINCT FROM OLD.width
    OR NEW.height IS DISTINCT FROM OLD.height
    OR NEW.has_transparency IS DISTINCT FROM OLD.has_transparency
    OR NEW.uploaded_by IS DISTINCT FROM OLD.uploaded_by
    OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'Company logo evidence is immutable';
  END IF;
  IF NEW.active IS DISTINCT FROM OLD.active
    AND current_setting('axora.brand_publication',true)<>'on' THEN
    RAISE EXCEPTION 'Logo activation requires controlled publication';
  END IF;
  RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION public.protect_company_brand_workflow()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.theme_id IS DISTINCT FROM OLD.theme_id
    OR NEW.company_id IS DISTINCT FROM OLD.company_id THEN
    RAISE EXCEPTION 'Company brand workflow identity is immutable';
  END IF;
  IF current_setting('axora.brand_workflow',true)<>'on' THEN
    RAISE EXCEPTION 'Company brand workflow transitions require a controlled function';
  END IF;
  IF NOT (
    (OLD.status='REVIEW_REQUIRED' AND NEW.status IN ('APPROVED','REJECTED','SUPERSEDED'))
    OR (OLD.status='APPROVED' AND NEW.status IN ('PUBLISHED','REJECTED','SUPERSEDED'))
    OR (OLD.status='PUBLISHED' AND NEW.status='SUPERSEDED')
  ) THEN
    RAISE EXCEPTION 'Invalid company brand workflow transition';
  END IF;
  RETURN NEW;
END
$$;

CREATE OR REPLACE FUNCTION public.protect_company_brand_event()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'Company brand workflow events are append-only';
END
$$;

DROP TRIGGER IF EXISTS protect_company_brand_themes
  ON public.company_brand_themes;
CREATE TRIGGER protect_company_brand_themes
BEFORE UPDATE ON public.company_brand_themes
FOR EACH ROW EXECUTE FUNCTION public.protect_company_brand_theme();

DROP TRIGGER IF EXISTS protect_company_brand_logos
  ON public.company_logos;
CREATE TRIGGER protect_company_brand_logos
BEFORE UPDATE ON public.company_logos
FOR EACH ROW EXECUTE FUNCTION public.protect_company_brand_logo();

DROP TRIGGER IF EXISTS protect_company_brand_workflows
  ON public.company_brand_theme_workflows;
CREATE TRIGGER protect_company_brand_workflows
BEFORE UPDATE ON public.company_brand_theme_workflows
FOR EACH ROW EXECUTE FUNCTION public.protect_company_brand_workflow();

DROP TRIGGER IF EXISTS protect_company_brand_events
  ON public.company_brand_theme_events;
CREATE TRIGGER protect_company_brand_events
BEFORE UPDATE OR DELETE ON public.company_brand_theme_events
FOR EACH ROW EXECUTE FUNCTION public.protect_company_brand_event();

DROP TRIGGER IF EXISTS company_brand_theme_workflows_audit
  ON public.company_brand_theme_workflows;
CREATE TRIGGER company_brand_theme_workflows_audit
AFTER INSERT OR UPDATE OR DELETE ON public.company_brand_theme_workflows
FOR EACH ROW EXECUTE FUNCTION public.audit_change();

CREATE OR REPLACE FUNCTION public.axora_record_company_brand_event(
  p_theme_id uuid,
  p_company_id uuid,
  p_source_logo_id uuid,
  p_from_status text,
  p_status text,
  p_action text,
  p_reason text,
  p_actor_user_id uuid,
  p_role_assignment_id uuid,
  p_at timestamptz
)
RETURNS uuid
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp
AS $$
DECLARE next_version integer; event_id uuid;
BEGIN
  SELECT COALESCE(max(event_version),0)+1 INTO next_version
  FROM public.company_brand_theme_events WHERE theme_id=p_theme_id;
  INSERT INTO public.company_brand_theme_events(
    theme_id,company_id,source_logo_id,event_version,from_status,status,
    action,reason,actor_id,role_assignment_id,created_at
  ) VALUES (
    p_theme_id,p_company_id,p_source_logo_id,next_version,p_from_status,
    p_status,p_action,p_reason,p_actor_user_id,p_role_assignment_id,p_at
  ) RETURNING id INTO event_id;
  RETURN event_id;
END
$$;

CREATE OR REPLACE FUNCTION public.axora_supersede_open_company_brand_reviews(
  p_company_id uuid,
  p_actor_user_id uuid,
  p_role_assignment_id uuid,
  p_reason text,
  p_at timestamptz
)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp
AS $$
DECLARE current_review record;
BEGIN
  PERFORM set_config('axora.brand_workflow','on',true);
  FOR current_review IN
    SELECT workflow.theme_id,workflow.status,theme.source_logo_id
    FROM public.company_brand_theme_workflows workflow
    JOIN public.company_brand_themes theme ON theme.id=workflow.theme_id
    WHERE workflow.company_id=p_company_id
      AND workflow.status IN ('REVIEW_REQUIRED','APPROVED')
    FOR UPDATE OF workflow
  LOOP
    UPDATE public.company_brand_theme_workflows
    SET status='SUPERSEDED',updated_by=p_actor_user_id,updated_at=p_at
    WHERE theme_id=current_review.theme_id;
    PERFORM public.axora_record_company_brand_event(
      current_review.theme_id,p_company_id,current_review.source_logo_id,
      current_review.status,'SUPERSEDED','SUPERSEDED',p_reason,
      p_actor_user_id,p_role_assignment_id,p_at
    );
  END LOOP;
END
$$;

CREATE OR REPLACE FUNCTION public.axora_brand_actor_can_view(
  p_snapshot jsonb,
  p_actor_user_id uuid,
  p_company_id uuid,
  p_at timestamptz
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp
AS $$
  SELECT public.axora_company_actor_is_owner(p_snapshot)
    OR (
      p_snapshot->>'accountKind'='PLATFORM'
      AND p_snapshot->>'roleKey'='CLIENT_ACCOUNT_MANAGER'
      AND public.axora_company_assignment_is_active(
        p_actor_user_id,p_company_id,p_at
      )
    )
    OR public.axora_snapshot_scope_contains(
      p_snapshot,'COMPANY',p_company_id,NULL,NULL,NULL
    )
$$;

CREATE OR REPLACE FUNCTION public.axora_create_company_brand_draft(
  p_actor_user_id uuid,
  p_actor_role_assignment_id uuid,
  p_company_id uuid,
  p_file_name text,
  p_content_type text,
  p_logo_content bytea,
  p_sha256 text,
  p_width integer,
  p_height integer,
  p_has_transparency boolean,
  p_algorithm_version text,
  p_tokens jsonb,
  p_extraction_summary jsonb,
  p_contrast_summary jsonb,
  p_manual_overrides jsonb,
  p_page_configuration jsonb,
  p_logo_variant text,
  p_logo_placement text,
  p_theme_preference text,
  p_source_theme_id uuid,
  p_reason text,
  p_at timestamptz DEFAULT now()
)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp
AS $$
DECLARE actor_snapshot jsonb; company_row record; logo_id uuid; theme_id uuid;
  logo_version integer; theme_version integer;
BEGIN
  actor_snapshot:=public.axora_live_authorization_snapshot(
    p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  SELECT company.id INTO company_row
  FROM public.companies company
  WHERE company.id=p_company_id AND company.lifecycle_status<>'ARCHIVED'
  FOR UPDATE;
  IF actor_snapshot IS NULL OR company_row.id IS NULL
    OR NOT public.axora_company_actor_has_permission(
      actor_snapshot,p_actor_user_id,p_company_id,
      'company.portal.preview',p_at
    )
    OR p_logo_content IS NULL
    OR octet_length(p_logo_content) NOT BETWEEN 1 AND 2097152
    OR p_content_type NOT IN ('image/jpeg','image/png','image/webp')
    OR p_sha256 !~ '^[0-9a-f]{64}$'
    OR p_width NOT BETWEEN 1 AND 4096
    OR p_height NOT BETWEEN 1 AND 4096
    OR char_length(btrim(p_file_name)) NOT BETWEEN 1 AND 255
    OR char_length(btrim(p_algorithm_version)) NOT BETWEEN 1 AND 80
    OR char_length(btrim(p_reason)) NOT BETWEEN 3 AND 1000
    OR NOT public.axora_brand_tokens_valid(p_tokens)
    OR NOT public.axora_brand_contrast_summary_valid(p_contrast_summary)
    OR NOT public.axora_brand_page_configuration_valid(p_page_configuration)
    OR jsonb_typeof(p_extraction_summary)<>'object'
    OR jsonb_typeof(p_manual_overrides)<>'object'
    OR char_length(p_manual_overrides::text)>16384
    OR p_logo_variant NOT IN ('ORIGINAL','MONOCHROME','INVERTED')
    OR p_logo_placement NOT IN ('HEADER_START','HEADER_CENTER')
    OR p_theme_preference NOT IN ('LIGHT','DARK') THEN
    RETURN NULL;
  END IF;
  IF p_source_theme_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.company_brand_themes
    WHERE id=p_source_theme_id AND company_id=p_company_id
  ) THEN
    RETURN NULL;
  END IF;

  PERFORM public.axora_supersede_open_company_brand_reviews(
    p_company_id,p_actor_user_id,p_actor_role_assignment_id,
    'Superseded by a newly generated logo draft',p_at
  );

  SELECT logo.id INTO logo_id
  FROM public.company_logos logo
  WHERE logo.company_id=p_company_id AND logo.sha256=p_sha256
  FOR UPDATE;
  IF logo_id IS NULL THEN
    SELECT COALESCE(max(version),0)+1 INTO logo_version
    FROM public.company_logos WHERE company_id=p_company_id;
    INSERT INTO public.company_logos(
      company_id,version,file_name,content_type,logo_content,sha256,
      width,height,has_transparency,active,uploaded_by,created_at
    ) VALUES (
      p_company_id,logo_version,btrim(p_file_name),p_content_type,
      p_logo_content,p_sha256,p_width,p_height,p_has_transparency,
      false,p_actor_user_id,p_at
    ) RETURNING id INTO logo_id;
  END IF;

  SELECT COALESCE(max(version),0)+1 INTO theme_version
  FROM public.company_brand_themes WHERE company_id=p_company_id;
  INSERT INTO public.company_brand_themes(
    company_id,source_logo_id,version,algorithm_version,
    primary_color,primary_hover,primary_active,secondary_color,accent_color,
    primary_foreground,secondary_foreground,page_background,
    dark_page_background,surface_color,dark_surface_color,muted_surface,
    border_color,dark_border_color,text_color,inverse_text_color,
    icon_color,inverse_icon_color,success_color,warning_color,danger_color,
    focus_ring,link_color,chart_colors,extraction_summary,contrast_summary,
    active,created_by,created_at,logo_variant,logo_placement,theme_preference,
    page_configuration,manual_overrides,source_theme_id
  ) VALUES (
    p_company_id,logo_id,theme_version,btrim(p_algorithm_version),
    p_tokens->>'primary',p_tokens->>'primaryHover',
    p_tokens->>'primaryActive',p_tokens->>'secondary',p_tokens->>'accent',
    p_tokens->>'primaryForeground',p_tokens->>'secondaryForeground',
    p_tokens->>'pageBackground',p_tokens->>'darkPageBackground',
    p_tokens->>'surface',p_tokens->>'darkSurface',p_tokens->>'mutedSurface',
    p_tokens->>'border',p_tokens->>'darkBorder',p_tokens->>'text',
    p_tokens->>'textInverse',p_tokens->>'icon',p_tokens->>'iconInverse',
    p_tokens->>'success',p_tokens->>'warning',p_tokens->>'danger',
    p_tokens->>'focusRing',p_tokens->>'link',
    ARRAY(SELECT jsonb_array_elements_text(p_tokens->'chart')),
    p_extraction_summary,p_contrast_summary,false,p_actor_user_id,p_at,
    p_logo_variant,p_logo_placement,p_theme_preference,
    p_page_configuration,p_manual_overrides,p_source_theme_id
  ) RETURNING id INTO theme_id;

  INSERT INTO public.company_brand_theme_workflows(
    theme_id,company_id,status,updated_by,updated_at
  ) VALUES (
    theme_id,p_company_id,'REVIEW_REQUIRED',p_actor_user_id,p_at
  );
  PERFORM public.axora_record_company_brand_event(
    theme_id,p_company_id,logo_id,NULL,'LOGO_UPLOADED','LOGO_UPLOADED',
    p_reason,p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  PERFORM public.axora_record_company_brand_event(
    theme_id,p_company_id,logo_id,'LOGO_UPLOADED','ANALYSIS_QUEUED',
    'ANALYSIS_QUEUED',p_reason,p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  PERFORM public.axora_record_company_brand_event(
    theme_id,p_company_id,logo_id,'ANALYSIS_QUEUED','DRAFT_GENERATED',
    'DRAFT_GENERATED',p_reason,p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  PERFORM public.axora_record_company_brand_event(
    theme_id,p_company_id,logo_id,'DRAFT_GENERATED','REVIEW_REQUIRED',
    'REVIEW_REQUESTED',p_reason,p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  RETURN jsonb_build_object(
    'status','REVIEW_REQUIRED','themeId',theme_id,'logoId',logo_id
  );
END
$$;

CREATE OR REPLACE FUNCTION public.axora_create_company_brand_variant(
  p_actor_user_id uuid,
  p_actor_role_assignment_id uuid,
  p_company_id uuid,
  p_base_theme_id uuid,
  p_algorithm_version text,
  p_tokens jsonb,
  p_extraction_summary jsonb,
  p_contrast_summary jsonb,
  p_manual_overrides jsonb,
  p_page_configuration jsonb,
  p_logo_variant text,
  p_logo_placement text,
  p_theme_preference text,
  p_reason text,
  p_at timestamptz DEFAULT now()
)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp
AS $$
DECLARE actor_snapshot jsonb; company_row record; base_theme record;
  theme_id uuid; theme_version integer;
BEGIN
  actor_snapshot:=public.axora_live_authorization_snapshot(
    p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  SELECT company.id INTO company_row
  FROM public.companies company
  WHERE company.id=p_company_id AND company.lifecycle_status<>'ARCHIVED'
  FOR UPDATE;
  SELECT theme.id,theme.source_logo_id INTO base_theme
  FROM public.company_brand_themes theme
  WHERE theme.id=p_base_theme_id AND theme.company_id=p_company_id;
  IF actor_snapshot IS NULL OR company_row.id IS NULL OR base_theme.id IS NULL
    OR NOT public.axora_company_actor_has_permission(
      actor_snapshot,p_actor_user_id,p_company_id,
      'company.portal.preview',p_at
    )
    OR char_length(btrim(p_algorithm_version)) NOT BETWEEN 1 AND 80
    OR char_length(btrim(p_reason)) NOT BETWEEN 3 AND 1000
    OR NOT public.axora_brand_tokens_valid(p_tokens)
    OR NOT public.axora_brand_contrast_summary_valid(p_contrast_summary)
    OR NOT public.axora_brand_page_configuration_valid(p_page_configuration)
    OR jsonb_typeof(p_extraction_summary)<>'object'
    OR jsonb_typeof(p_manual_overrides)<>'object'
    OR char_length(p_manual_overrides::text)>16384
    OR p_logo_variant NOT IN ('ORIGINAL','MONOCHROME','INVERTED')
    OR p_logo_placement NOT IN ('HEADER_START','HEADER_CENTER')
    OR p_theme_preference NOT IN ('LIGHT','DARK') THEN
    RETURN NULL;
  END IF;

  PERFORM public.axora_supersede_open_company_brand_reviews(
    p_company_id,p_actor_user_id,p_actor_role_assignment_id,
    'Superseded by a revised company brand draft',p_at
  );
  SELECT COALESCE(max(version),0)+1 INTO theme_version
  FROM public.company_brand_themes WHERE company_id=p_company_id;
  INSERT INTO public.company_brand_themes(
    company_id,source_logo_id,version,algorithm_version,
    primary_color,primary_hover,primary_active,secondary_color,accent_color,
    primary_foreground,secondary_foreground,page_background,
    dark_page_background,surface_color,dark_surface_color,muted_surface,
    border_color,dark_border_color,text_color,inverse_text_color,
    icon_color,inverse_icon_color,success_color,warning_color,danger_color,
    focus_ring,link_color,chart_colors,extraction_summary,contrast_summary,
    active,created_by,created_at,logo_variant,logo_placement,theme_preference,
    page_configuration,manual_overrides,source_theme_id
  ) VALUES (
    p_company_id,base_theme.source_logo_id,theme_version,btrim(p_algorithm_version),
    p_tokens->>'primary',p_tokens->>'primaryHover',
    p_tokens->>'primaryActive',p_tokens->>'secondary',p_tokens->>'accent',
    p_tokens->>'primaryForeground',p_tokens->>'secondaryForeground',
    p_tokens->>'pageBackground',p_tokens->>'darkPageBackground',
    p_tokens->>'surface',p_tokens->>'darkSurface',p_tokens->>'mutedSurface',
    p_tokens->>'border',p_tokens->>'darkBorder',p_tokens->>'text',
    p_tokens->>'textInverse',p_tokens->>'icon',p_tokens->>'iconInverse',
    p_tokens->>'success',p_tokens->>'warning',p_tokens->>'danger',
    p_tokens->>'focusRing',p_tokens->>'link',
    ARRAY(SELECT jsonb_array_elements_text(p_tokens->'chart')),
    p_extraction_summary,p_contrast_summary,false,p_actor_user_id,p_at,
    p_logo_variant,p_logo_placement,p_theme_preference,
    p_page_configuration,p_manual_overrides,p_base_theme_id
  ) RETURNING id INTO theme_id;
  INSERT INTO public.company_brand_theme_workflows(
    theme_id,company_id,status,updated_by,updated_at
  ) VALUES (
    theme_id,p_company_id,'REVIEW_REQUIRED',p_actor_user_id,p_at
  );
  PERFORM public.axora_record_company_brand_event(
    theme_id,p_company_id,base_theme.source_logo_id,NULL,'DRAFT_GENERATED',
    'DRAFT_GENERATED',p_reason,p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  PERFORM public.axora_record_company_brand_event(
    theme_id,p_company_id,base_theme.source_logo_id,'DRAFT_GENERATED',
    'REVIEW_REQUIRED','REVIEW_REQUESTED',p_reason,
    p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  RETURN jsonb_build_object(
    'status','REVIEW_REQUIRED','themeId',theme_id,
    'logoId',base_theme.source_logo_id
  );
END
$$;

CREATE OR REPLACE FUNCTION public.axora_transition_company_brand_theme(
  p_actor_user_id uuid,
  p_actor_role_assignment_id uuid,
  p_company_id uuid,
  p_theme_id uuid,
  p_action text,
  p_reason text,
  p_at timestamptz DEFAULT now()
)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp
AS $$
DECLARE actor_snapshot jsonb; company_row record; selected record;
  current_published record; required_permission text;
BEGIN
  actor_snapshot:=public.axora_live_authorization_snapshot(
    p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  SELECT company.id INTO company_row
  FROM public.companies company
  WHERE company.id=p_company_id AND company.lifecycle_status<>'ARCHIVED'
  FOR UPDATE;
  required_permission:=CASE
    WHEN p_action='PUBLISH' THEN 'company.portal.publish'
    ELSE 'company.portal.preview'
  END;
  IF actor_snapshot IS NULL OR company_row.id IS NULL
    OR p_action NOT IN ('APPROVE','REJECT','PUBLISH')
    OR char_length(btrim(p_reason)) NOT BETWEEN 3 AND 1000
    OR NOT public.axora_company_actor_has_permission(
      actor_snapshot,p_actor_user_id,p_company_id,required_permission,p_at
    ) THEN
    RETURN NULL;
  END IF;
  SELECT workflow.status,theme.source_logo_id,theme.contrast_summary,
    theme.active
  INTO selected
  FROM public.company_brand_theme_workflows workflow
  JOIN public.company_brand_themes theme ON theme.id=workflow.theme_id
  WHERE workflow.theme_id=p_theme_id AND workflow.company_id=p_company_id
  FOR UPDATE OF workflow,theme;
  IF selected.status IS NULL THEN RETURN NULL; END IF;

  PERFORM set_config('axora.brand_workflow','on',true);
  IF p_action='APPROVE' THEN
    IF selected.status<>'REVIEW_REQUIRED' THEN
      RETURN jsonb_build_object('status','INVALID_STATE','themeId',p_theme_id);
    END IF;
    IF COALESCE((selected.contrast_summary->>'passes')::boolean,false)=false THEN
      RETURN jsonb_build_object('status','CONTRAST_BLOCKED','themeId',p_theme_id);
    END IF;
    UPDATE public.company_brand_theme_workflows
    SET status='APPROVED',updated_by=p_actor_user_id,updated_at=p_at
    WHERE theme_id=p_theme_id;
    PERFORM public.axora_record_company_brand_event(
      p_theme_id,p_company_id,selected.source_logo_id,'REVIEW_REQUIRED',
      'APPROVED','APPROVED',p_reason,p_actor_user_id,
      p_actor_role_assignment_id,p_at
    );
    RETURN jsonb_build_object('status','APPROVED','themeId',p_theme_id);
  END IF;

  IF p_action='REJECT' THEN
    IF selected.status NOT IN ('REVIEW_REQUIRED','APPROVED') THEN
      RETURN jsonb_build_object('status','INVALID_STATE','themeId',p_theme_id);
    END IF;
    UPDATE public.company_brand_theme_workflows
    SET status='REJECTED',updated_by=p_actor_user_id,updated_at=p_at
    WHERE theme_id=p_theme_id;
    PERFORM public.axora_record_company_brand_event(
      p_theme_id,p_company_id,selected.source_logo_id,selected.status,
      'REJECTED','REJECTED',p_reason,p_actor_user_id,
      p_actor_role_assignment_id,p_at
    );
    RETURN jsonb_build_object('status','REJECTED','themeId',p_theme_id);
  END IF;

  IF selected.status<>'APPROVED' THEN
    RETURN jsonb_build_object('status','INVALID_STATE','themeId',p_theme_id);
  END IF;
  IF COALESCE((selected.contrast_summary->>'passes')::boolean,false)=false THEN
    RETURN jsonb_build_object('status','CONTRAST_BLOCKED','themeId',p_theme_id);
  END IF;

  SELECT theme.id,workflow.status,theme.source_logo_id
  INTO current_published
  FROM public.company_brand_themes theme
  JOIN public.company_brand_theme_workflows workflow ON workflow.theme_id=theme.id
  WHERE theme.company_id=p_company_id AND theme.active
  FOR UPDATE OF theme,workflow;
  PERFORM set_config('axora.brand_publication','on',true);
  IF current_published.id IS NOT NULL THEN
    UPDATE public.company_brand_themes SET active=false
    WHERE id=current_published.id;
    UPDATE public.company_brand_theme_workflows
    SET status='SUPERSEDED',updated_by=p_actor_user_id,updated_at=p_at
    WHERE theme_id=current_published.id;
    PERFORM public.axora_record_company_brand_event(
      current_published.id,p_company_id,current_published.source_logo_id,
      current_published.status,'SUPERSEDED','SUPERSEDED',
      'Superseded by an approved published company theme',
      p_actor_user_id,p_actor_role_assignment_id,p_at
    );
  END IF;
  UPDATE public.company_logos SET active=false
  WHERE company_id=p_company_id AND active;
  UPDATE public.company_logos SET active=true
  WHERE id=selected.source_logo_id AND company_id=p_company_id;
  UPDATE public.company_brand_themes SET active=true WHERE id=p_theme_id;
  UPDATE public.company_brand_theme_workflows
  SET status='PUBLISHED',updated_by=p_actor_user_id,updated_at=p_at
  WHERE theme_id=p_theme_id;
  PERFORM public.axora_record_company_brand_event(
    p_theme_id,p_company_id,selected.source_logo_id,'APPROVED','PUBLISHED',
    'PUBLISHED',p_reason,p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  RETURN jsonb_build_object('status','PUBLISHED','themeId',p_theme_id);
END
$$;

CREATE OR REPLACE FUNCTION public.axora_rollback_company_brand_theme(
  p_actor_user_id uuid,
  p_actor_role_assignment_id uuid,
  p_company_id uuid,
  p_target_theme_id uuid,
  p_reason text,
  p_at timestamptz DEFAULT now()
)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp
AS $$
DECLARE actor_snapshot jsonb; company_row record; target record;
  current_published record; next_version integer; new_theme_id uuid;
BEGIN
  actor_snapshot:=public.axora_live_authorization_snapshot(
    p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  SELECT company.id INTO company_row
  FROM public.companies company
  WHERE company.id=p_company_id AND company.lifecycle_status<>'ARCHIVED'
  FOR UPDATE;
  SELECT theme.* INTO target
  FROM public.company_brand_themes theme
  WHERE theme.id=p_target_theme_id AND theme.company_id=p_company_id
    AND EXISTS (
      SELECT 1 FROM public.company_brand_theme_events event
      WHERE event.theme_id=theme.id AND event.status='PUBLISHED'
    )
  FOR UPDATE;
  IF actor_snapshot IS NULL OR company_row.id IS NULL OR target.id IS NULL
    OR char_length(btrim(p_reason)) NOT BETWEEN 3 AND 1000
    OR NOT public.axora_company_actor_has_permission(
      actor_snapshot,p_actor_user_id,p_company_id,
      'company.portal.publish',p_at
    ) THEN
    RETURN NULL;
  END IF;
  IF target.active THEN
    RETURN jsonb_build_object(
      'status','UNCHANGED','themeId',p_target_theme_id
    );
  END IF;
  SELECT theme.id,workflow.status,theme.source_logo_id
  INTO current_published
  FROM public.company_brand_themes theme
  JOIN public.company_brand_theme_workflows workflow ON workflow.theme_id=theme.id
  WHERE theme.company_id=p_company_id AND theme.active
  FOR UPDATE OF theme,workflow;
  PERFORM set_config('axora.brand_workflow','on',true);
  PERFORM set_config('axora.brand_publication','on',true);
  IF current_published.id IS NOT NULL THEN
    UPDATE public.company_brand_themes SET active=false
    WHERE id=current_published.id;
    UPDATE public.company_brand_theme_workflows
    SET status='SUPERSEDED',updated_by=p_actor_user_id,updated_at=p_at
    WHERE theme_id=current_published.id;
    PERFORM public.axora_record_company_brand_event(
      current_published.id,p_company_id,current_published.source_logo_id,
      current_published.status,'SUPERSEDED','SUPERSEDED',
      'Superseded by a controlled company theme rollback',
      p_actor_user_id,p_actor_role_assignment_id,p_at
    );
  END IF;
  UPDATE public.company_logos SET active=false
  WHERE company_id=p_company_id AND active;
  UPDATE public.company_logos SET active=true
  WHERE id=target.source_logo_id AND company_id=p_company_id;
  SELECT COALESCE(max(version),0)+1 INTO next_version
  FROM public.company_brand_themes WHERE company_id=p_company_id;
  INSERT INTO public.company_brand_themes(
    company_id,source_logo_id,version,algorithm_version,
    primary_color,primary_hover,primary_active,secondary_color,accent_color,
    primary_foreground,secondary_foreground,page_background,
    dark_page_background,surface_color,dark_surface_color,muted_surface,
    border_color,dark_border_color,text_color,inverse_text_color,
    icon_color,inverse_icon_color,success_color,warning_color,danger_color,
    focus_ring,link_color,chart_colors,extraction_summary,contrast_summary,
    active,created_by,created_at,logo_variant,logo_placement,theme_preference,
    page_configuration,manual_overrides,source_theme_id,rollback_of_theme_id
  ) VALUES (
    p_company_id,target.source_logo_id,next_version,target.algorithm_version,
    target.primary_color,target.primary_hover,target.primary_active,
    target.secondary_color,target.accent_color,target.primary_foreground,
    target.secondary_foreground,target.page_background,
    target.dark_page_background,target.surface_color,target.dark_surface_color,
    target.muted_surface,target.border_color,target.dark_border_color,
    target.text_color,target.inverse_text_color,target.icon_color,
    target.inverse_icon_color,target.success_color,target.warning_color,
    target.danger_color,target.focus_ring,target.link_color,target.chart_colors,
    target.extraction_summary,target.contrast_summary,true,p_actor_user_id,p_at,
    target.logo_variant,target.logo_placement,target.theme_preference,
    target.page_configuration,
    jsonb_build_object('rollbackOfThemeId',p_target_theme_id),
    p_target_theme_id,p_target_theme_id
  ) RETURNING id INTO new_theme_id;
  INSERT INTO public.company_brand_theme_workflows(
    theme_id,company_id,status,updated_by,updated_at
  ) VALUES (
    new_theme_id,p_company_id,'PUBLISHED',p_actor_user_id,p_at
  );
  PERFORM public.axora_record_company_brand_event(
    new_theme_id,p_company_id,target.source_logo_id,NULL,'PUBLISHED',
    'ROLLBACK_PUBLISHED',p_reason,p_actor_user_id,
    p_actor_role_assignment_id,p_at
  );
  RETURN jsonb_build_object(
    'status','PUBLISHED','themeId',new_theme_id,
    'rollbackOfThemeId',p_target_theme_id
  );
END
$$;

CREATE OR REPLACE FUNCTION public.axora_company_brand_theme_json(
  p_theme_id uuid
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp
AS $$
  SELECT jsonb_build_object(
    'id',theme.id,
    'companyId',theme.company_id,
    'sourceLogoId',theme.source_logo_id,
    'sourceLogoHash',logo.sha256,
    'version',theme.version,
    'algorithmVersion',theme.algorithm_version,
    'status',workflow.status,
    'active',theme.active,
    'tokens',jsonb_build_object(
      'primary',theme.primary_color,
      'primaryHover',theme.primary_hover,
      'primaryActive',theme.primary_active,
      'secondary',theme.secondary_color,
      'accent',theme.accent_color,
      'primaryForeground',theme.primary_foreground,
      'secondaryForeground',theme.secondary_foreground,
      'pageBackground',theme.page_background,
      'darkPageBackground',theme.dark_page_background,
      'surface',theme.surface_color,
      'darkSurface',theme.dark_surface_color,
      'mutedSurface',theme.muted_surface,
      'border',theme.border_color,
      'darkBorder',theme.dark_border_color,
      'text',theme.text_color,
      'textInverse',theme.inverse_text_color,
      'icon',theme.icon_color,
      'iconInverse',theme.inverse_icon_color,
      'success',theme.success_color,
      'warning',theme.warning_color,
      'danger',theme.danger_color,
      'focusRing',theme.focus_ring,
      'link',theme.link_color,
      'chart',to_jsonb(theme.chart_colors)
    ),
    'extractionSummary',theme.extraction_summary,
    'contrastSummary',theme.contrast_summary,
    'manualOverrides',theme.manual_overrides,
    'pageConfiguration',theme.page_configuration,
    'logoVariant',theme.logo_variant,
    'logoPlacement',theme.logo_placement,
    'themePreference',theme.theme_preference,
    'sourceThemeId',theme.source_theme_id,
    'rollbackOfThemeId',theme.rollback_of_theme_id,
    'createdAt',theme.created_at,
    'createdBy',CASE WHEN creator.id IS NULL THEN NULL ELSE jsonb_build_object(
      'id',creator.id,'name',creator.display_name
    ) END,
    'reviewedBy',(
      SELECT jsonb_build_object(
        'id',reviewer.id,'name',reviewer.display_name,'at',event.created_at
      )
      FROM public.company_brand_theme_events event
      LEFT JOIN public.users reviewer ON reviewer.id=event.actor_id
      WHERE event.theme_id=theme.id AND event.status='APPROVED'
      ORDER BY event.created_at DESC,event.id DESC LIMIT 1
    ),
    'publishedBy',(
      SELECT jsonb_build_object(
        'id',publisher.id,'name',publisher.display_name,'at',event.created_at
      )
      FROM public.company_brand_theme_events event
      LEFT JOIN public.users publisher ON publisher.id=event.actor_id
      WHERE event.theme_id=theme.id AND event.status='PUBLISHED'
      ORDER BY event.created_at DESC,event.id DESC LIMIT 1
    )
  )
  FROM public.company_brand_themes theme
  JOIN public.company_logos logo ON logo.id=theme.source_logo_id
  JOIN public.company_brand_theme_workflows workflow
    ON workflow.theme_id=theme.id
  LEFT JOIN public.users creator ON creator.id=theme.created_by
  WHERE theme.id=p_theme_id
$$;

CREATE OR REPLACE FUNCTION public.axora_company_brand_review_workspace(
  p_actor_user_id uuid,
  p_actor_role_assignment_id uuid,
  p_company_id uuid,
  p_at timestamptz DEFAULT now()
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp
AS $$
DECLARE actor_snapshot jsonb; company_row record; themes jsonb; events jsonb;
BEGIN
  actor_snapshot:=public.axora_live_authorization_snapshot(
    p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  SELECT company.id,company.name,company.company_code AS code INTO company_row
  FROM public.companies company
  WHERE company.id=p_company_id AND company.lifecycle_status<>'ARCHIVED';
  IF actor_snapshot IS NULL OR company_row.id IS NULL
    OR NOT public.axora_company_actor_has_permission(
      actor_snapshot,p_actor_user_id,p_company_id,
      'company.portal.preview',p_at
    ) THEN
    RETURN NULL;
  END IF;
  SELECT COALESCE(
    jsonb_agg(
      public.axora_company_brand_theme_json(theme.id)
      ORDER BY theme.version DESC
    ),
    '[]'::jsonb
  ) INTO themes
  FROM public.company_brand_themes theme
  WHERE theme.company_id=p_company_id;
  SELECT COALESCE(jsonb_agg(to_jsonb(event_row)), '[]'::jsonb)
  INTO events
  FROM (
    SELECT event.id,event.theme_id AS "themeId",
      event.event_version AS "eventVersion",
      event.from_status AS "fromStatus",event.status,event.action,
      event.reason,event.created_at AS "createdAt",
      CASE WHEN actor.id IS NULL THEN NULL ELSE jsonb_build_object(
        'id',actor.id,'name',actor.display_name
      ) END AS actor
    FROM public.company_brand_theme_events event
    LEFT JOIN public.users actor ON actor.id=event.actor_id
    WHERE event.company_id=p_company_id
    ORDER BY event.created_at DESC,event.id DESC
    LIMIT 100
  ) event_row;
  RETURN jsonb_build_object(
    'company',jsonb_build_object(
      'id',company_row.id,'name',company_row.name,'code',company_row.code
    ),
    'canPublish',public.axora_company_actor_has_permission(
      actor_snapshot,p_actor_user_id,p_company_id,
      'company.portal.publish',p_at
    ),
    'publishedThemeId',(
      SELECT id FROM public.company_brand_themes
      WHERE company_id=p_company_id AND active LIMIT 1
    ),
    'themes',themes,
    'events',events
  );
END
$$;

CREATE OR REPLACE FUNCTION public.axora_active_company_brand(
  p_actor_user_id uuid,
  p_actor_role_assignment_id uuid,
  p_company_id uuid,
  p_at timestamptz DEFAULT now()
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp
AS $$
DECLARE actor_snapshot jsonb; company_row record; theme_row record;
  payload jsonb;
BEGIN
  actor_snapshot:=public.axora_live_authorization_snapshot(
    p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  SELECT company.id,company.name INTO company_row
  FROM public.companies company
  WHERE company.id=p_company_id AND company.active;
  IF actor_snapshot IS NULL OR company_row.id IS NULL
    OR NOT public.axora_brand_actor_can_view(
      actor_snapshot,p_actor_user_id,p_company_id,p_at
    ) THEN
    RETURN NULL;
  END IF;
  SELECT theme.id,logo.content_type INTO theme_row
  FROM public.company_brand_themes theme
  JOIN public.company_logos logo ON logo.id=theme.source_logo_id
  WHERE theme.company_id=p_company_id AND theme.active
  LIMIT 1;
  IF theme_row.id IS NULL THEN RETURN NULL; END IF;
  payload:=public.axora_company_brand_theme_json(theme_row.id);
  RETURN payload || jsonb_build_object(
    'companyId',company_row.id,
    'companyName',company_row.name,
    'logoContentType',theme_row.content_type
  );
END
$$;

CREATE OR REPLACE FUNCTION public.axora_company_brand_logo(
  p_actor_user_id uuid,
  p_actor_role_assignment_id uuid,
  p_company_id uuid,
  p_theme_id uuid,
  p_at timestamptz DEFAULT now()
)
RETURNS TABLE(
  bytes bytea,
  content_type text,
  sha256 text
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp
AS $$
DECLARE actor_snapshot jsonb; authorized boolean:=false;
BEGIN
  actor_snapshot:=public.axora_live_authorization_snapshot(
    p_actor_user_id,p_actor_role_assignment_id,p_at
  );
  IF actor_snapshot IS NULL THEN RETURN; END IF;
  IF p_theme_id IS NULL THEN
    authorized:=public.axora_brand_actor_can_view(
      actor_snapshot,p_actor_user_id,p_company_id,p_at
    );
  ELSE
    authorized:=public.axora_company_actor_has_permission(
      actor_snapshot,p_actor_user_id,p_company_id,
      'company.portal.preview',p_at
    );
  END IF;
  IF NOT authorized THEN RETURN; END IF;
  RETURN QUERY
  SELECT logo.logo_content,logo.content_type,logo.sha256
  FROM public.company_brand_themes theme
  JOIN public.company_logos logo ON logo.id=theme.source_logo_id
  JOIN public.companies company ON company.id=theme.company_id
  WHERE theme.company_id=p_company_id
    AND company.lifecycle_status<>'ARCHIVED'
    AND (
      (p_theme_id IS NULL AND theme.active)
      OR (p_theme_id IS NOT NULL AND theme.id=p_theme_id)
    )
  LIMIT 1;
END
$$;

ALTER TABLE public.company_logos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_logos FORCE ROW LEVEL SECURITY;
ALTER TABLE public.company_brand_themes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_brand_themes FORCE ROW LEVEL SECURITY;
ALTER TABLE public.company_brand_theme_workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_brand_theme_workflows FORCE ROW LEVEL SECURITY;
ALTER TABLE public.company_brand_theme_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_brand_theme_events FORCE ROW LEVEL SECURITY;

DO $brand_privileges$
DECLARE function_record record; app_role_exists boolean;
BEGIN
  app_role_exists:=EXISTS (
    SELECT 1 FROM pg_roles WHERE rolname='axora_app'
  );
  FOR function_record IN
    SELECT p.proname,p.oid::regprocedure::text AS signature
    FROM pg_proc p
    JOIN pg_namespace namespace ON namespace.oid=p.pronamespace
    WHERE namespace.nspname='public'
      AND p.proname=ANY(ARRAY[
        'axora_brand_page_configuration_valid',
        'axora_brand_tokens_valid',
        'axora_brand_contrast_summary_valid',
        'axora_record_company_brand_event',
        'axora_supersede_open_company_brand_reviews',
        'axora_brand_actor_can_view',
        'axora_create_company_brand_draft',
        'axora_create_company_brand_variant',
        'axora_transition_company_brand_theme',
        'axora_rollback_company_brand_theme',
        'axora_company_brand_theme_json',
        'axora_company_brand_review_workspace',
        'axora_active_company_brand',
        'axora_company_brand_logo'
      ])
  LOOP
    EXECUTE format(
      'REVOKE ALL ON FUNCTION %s FROM PUBLIC',
      function_record.signature
    );
    IF app_role_exists AND function_record.proname=ANY(ARRAY[
      'axora_create_company_brand_draft',
      'axora_create_company_brand_variant',
      'axora_transition_company_brand_theme',
      'axora_rollback_company_brand_theme',
      'axora_company_brand_review_workspace',
      'axora_active_company_brand',
      'axora_company_brand_logo'
    ]) THEN
      EXECUTE format(
        'GRANT EXECUTE ON FUNCTION %s TO axora_app',
        function_record.signature
      );
    END IF;
  END LOOP;
  IF app_role_exists THEN
    REVOKE ALL ON TABLE
      public.company_logos,
      public.company_brand_themes,
      public.company_brand_theme_workflows,
      public.company_brand_theme_events
    FROM axora_app;
  END IF;
END
$brand_privileges$;

COMMIT;
