import { PageHeader } from "@/components/PageHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { formatCurrency } from "@/lib/domain";
import { listProducts, listSuppliers } from "@/lib/repository";
import { createProductAction, setMasterActiveAction } from "../masters/actions";

export default async function ProductsPage() {
  const [products, suppliers] = await Promise.all([listProducts(), listSuppliers()]);
  return <><PageHeader eyebrow="Master data" title="Products" description="Stable product IDs, normalized categories, supplier links and duplicate warnings replace formula-generated spreadsheet references." />
    <section className="split-layout"><article className="panel"><div className="panel-header"><div><h2>Product master</h2><p>{products.length} products · {products.filter((item) => item.duplicateWarning).length} duplicate warning</p></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Category</th><th>Unit / MOQ</th><th>Preferred supplier</th><th>Buy / sell</th><th>Status</th><th>Action</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td><strong>{product.name}</strong><br /><span className="subtle">{product.code}</span></td><td>{product.category}<br /><span className="subtle">{product.subcategory}</span></td><td>{product.unit}<br /><span className="subtle">MOQ {product.minimumOrderQuantity}</span></td><td>{product.preferredSupplierName || "Not assigned"}</td><td>{formatCurrency(product.defaultBuyPrice)}<br /><span className="subtle">Sell {formatCurrency(product.defaultSellPrice)}</span></td><td><StatusBadge>{product.status}</StatusBadge></td><td><form action={setMasterActiveAction.bind(null, "products", product.id, product.status !== "Active")}><button className="button button-secondary" type="submit">{product.status === "Active" ? "Deactivate" : "Activate"}</button></form></td></tr>)}</tbody></table></div></article>
    <form action={createProductAction} className="panel form-panel"><h2>Add a product</h2><p>Case-insensitive duplicate checking runs before activation.</p><div className="form-grid">
      <label className="field-full">Product name<input name="name" required /></label><label>Category<select name="category"><option>Office Basics</option><option>Pantry / Hospitality</option><option>Cleaning & Hygiene</option><option>Printing & Branding / Marketing</option></select></label><label>Subcategory<input name="subcategory" required /></label>
      <label>Brand<input name="brand" /></label><label>Size<input name="size" /></label><label>Unit<select name="unit"><option>Piece</option><option>Pack</option><option>Box</option><option>Bottle</option><option>Roll</option><option>Carton</option><option>Ream</option><option>Jar</option><option>Sheet</option></select></label><label>Packaging<input name="packaging" /></label>
      <label>Buy price (RM)<input name="defaultBuyPrice" type="number" min="0" step="0.01" required /></label><label>Sell price (RM)<input name="defaultSellPrice" type="number" min="0" step="0.01" required /></label><label>Minimum quantity<input name="minimumOrderQuantity" type="number" min="0" step="0.01" defaultValue="1" /></label><label>Delivery SLA (days)<input name="deliverySlaDays" type="number" min="0" defaultValue="1" /></label>
      <label className="field-full">Preferred supplier<select name="preferredSupplierId" defaultValue=""><option value="">Not assigned</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.code} · {supplier.name}</option>)}</select></label><label className="field-full">Description / specification<textarea name="description" /></label>
    </div><div className="form-actions"><button className="button button-primary" type="submit">Add product</button></div></form></section></>;
}
